--[[
	#	MTA:DayZ Reserved Vehicles 2017 (C)
	#
	#	Author: Enargy
	#	Type: shared.
	#	File: source/shared/dayzitems.lua
	#
	#	All rights reserved to his developers.
]]

dayzItemTable = {
	{"Transfusor de Sangue"},
	{"Analgésicos"},
	{"Antibioticos"},
	{"Esteróides"},
	{"Morfina"},
	{"Kit de Primeiros Socorros"},
	{"Curativo"},
	{"Flecha"},
	{"Bolsa de Sangue (A+)"},
	{"Bolsa de Sangue (A-)"},
	{"Bolsa de Sangue (B+)"},
	{"Bolsa de Sangue (B-)"},
	{"Bolsa de Sangue (AB+)"},
	{"Bolsa de Sangue (AB-)"},
	{"Bolsa de Sangue (O+)"},
	{"Bolsa de Sangue (O-)"},
	-- ARMAS
	{"Bizon PP-19 SD"},
	{"CZ 550"},
	{"Dragunov"},
	{"MP5A5"},
	{"PDW"},
	{"Barret 50"},
	{"AKS-74U"},
	{"G28"},
	{"Benelli"},
	{"Remington 870"},
	{"Winchester 1866"},
	{"IMI Galil"},
	{"Beretta M92F"},
	{"M1911"},
	{"M9"},
	{"PGM Hecate"},
	{"AKS Gold"},
	{"FN FAL"},
	{"FN FNC"},
	{"AK-74 PSO"},
	{"AKS-74UN Kobra"},
	{"ACR"},
	{"AK-74"},
	{"Steyr AUG"},
	{"USP45"},
	{"USP45 SD"},
	{"G36C"},
	{"M16"},
	{"Ballesta"},
	{"Desert Eagle"},
	{"Revolver"},
	{"Machado"},
	{"Palanca"},
	{"Cuchillo"},
	{"M107"},
	{"Mk14-EBR"},
	{"AS50"},
	{"Mk-48"},
	{"PKM"},
	{"Granada"},
	{"Paraquedas"},
	{"M4A3 CCO"},
	{"M79"},
	{"M203"},
	{"AK-107 GL PSO"},
	-- MUNICIONES
	{"9x18mm"},
	{"9x19mm"},
	{"12 Gauge"},
	{"5.45x39mm"},
	{"5.56x45mm"},
	{"7.62x51mm"},
	{"7.62x54mm"},
	{"11.43x23mm"},
	{"1866 Slug"},
	{".308 Winchester"},
	-- MOCHILAS
	{"Mochila Militar"},	
	{"Mochila Livie"},		
	{"Mochila Rucksack"},		
	{"Mochila Alice"},
	{"Mochila Ossier"},
	{"Mochila Asalto"},	
	{"Mochila Coyote"},
	{"Mochila Krysset"},
	{"Mochila Gamespot"},
	{"Improvised Backpack"},
	{"Schoolar Backpack"},
	{"Cabo Backpack"},
	{"Assault Light Backpack"},
	{"Guillie Backpack"},
	{"Survivor Backpack"},
	{"Camping Backpack"},
	{"Mountain Light Backpack"},
	{"Mountain Backpack"},
	{"Czech Camo Backpack"},
	{"Coyote Camo Backpack"},
	{"SFG Army Camo Backpack"},
	-- OTROS
	{"Valla de alambre"},
	{"Lata vacia"},
	{"Lata de soda vacia"},
	{"Mina"},
	{"Armadilha para Urso"},
	{"Mina laser"},
	{"Bidon de gasolina"},
	{"Bidon vacio"},
	{"Tienda basica"},
	{"Bengala"},
	{"Garrafa de Água vacia"},	
	{"Mapa"},
	{"Pila de madera"},
	{"Bolsa Térmica"},
	{"GPS"},
	{"Caixa de Ferramentas"},
	{"Caixa de Fósforo"},
	{"Relógio"},
	{"Trozo de metal"},
	{"Óculos de Visão Noturna"},
	{"Óculos de Visão Termal"},
	{"Binóculos"},
	{"Casco de aviador"},
	{"Casco de moto"},
	{"Casco basico"},
	{"Casco de guerra"},
	{"Casco de aviador"},
	{"Chaleco de policia"},
	{"Chaleco civil"},
	{"Chaleco de guerra"},
	{"Traje Ghillie"},	
	{"Survivor Suit"},
	{"Police Suit"},
	-- PARTES DE UN VEHICULO
	{"Motor"},
	{"Bateria"},
	{"Tanque de combustible"},
	{"Neumatico"},
	{"Rotador"},
	-- ALIMENTICIOS
	{"Doritos"},
	{"Garrafa de Água"},
	{"Feijões Enlatados"},
	{"Macarrão Enlatado"},
	{"Sardinhas Enlatadas"},
	{"Salchichas Enlatadas"},
	{"Ração Militar"},
	{"Milho Enlatado"},
	{"Ervilhas Enlatadas"},
	{"Sopa Enlatada"},
	{"Porco Enlatado"},
	{"Frutas Enlatadas"},
	{"Sopa Enlatada de pescado"},
	{"Ravioles Enlatados"},
	{"Leite"},
	{"Carne Cozida"},
	{"Carne Crua"},
	{"Coca-Cola"},
	{"Mountain Dew"},
	{"Pepsi"},
}