--[[
	#	MTA:DayZ Reserved Vehicles 2017 (C)
	#
	#	Author: Enargy
	#	Type: shared.
	#	File: source/shared/dayzitems.lua
	#
	#	All rights reserved to his developers.
]]

dayzItemTable = {
	{"Transfusor de sangre"},
	{"Analgesicos"},
	{"Antibioticos"},
	{"Esteroides"},
	{"Morfina"},
	{"Botiquin"},
	{"Vendaje"},
	{"Flecha"},
	{"Bolsa de sangre (A+)"},
	{"Bolsa de sangre (A-)"},
	{"Bolsa de sangre (B+)"},
	{"Bolsa de sangre (B-)"},
	{"Bolsa de sangre (AB+)"},
	{"Bolsa de sangre (AB-)"},
	{"Bolsa de sangre (O+)"},
	{"Bolsa de sangre (O-)"},
	-- ARMAS
	{"Bizon PP-19 SD"},
	{"CZ 550"},
	{"Dragunov"},
	{"MP5A5"},
	{"PDW"},
	{"Barret 50"},
	{"AKS-74U"},
	{"G28"},
	{"Benelli"},
	{"Remington 870"},
	{"Winchester 1866"},
	{"IMI Galil"},
	{"Beretta M92F"},
	{"M1911"},
	{"M9"},
	{"PGM Hecate"},
	{"AKS Gold"},
	{"FN FAL"},
	{"FN FNC"},
	{"AK-74 PSO"},
	{"AKS-74UN Kobra"},
	{"ACR"},
	{"AK-74"},
	{"Steyr AUG"},
	{"USP45"},
	{"USP45 SD"},
	{"G36C"},
	{"M16"},
	{"Ballesta"},
	{"Desert Eagle"},
	{"Revolver"},
	{"Hacha"},
	{"Palanca"},
	{"Cuchillo"},
	{"M107"},
	{"Mk14-EBR"},
	{"AS50"},
	{"Mk-48"},
	{"PKM"},
	{"Granada"},
	{"Paracaidas"},
	{"M4A3 CCO"},
	{"M79"},
	{"M203"},
	{"AK-107 GL PSO"},
	-- MUNICIONES
	{"9x18mm"},
	{"9x19mm"},
	{"12 Gauge"},
	{"5.45x39mm"},
	{"5.56x45mm"},
	{"7.62x51mm"},
	{"7.62x54mm"},
	{"11.43x23mm"},
	{"1866 Slug"},
	{".308 Winchester"},
	-- MOCHILAS
	{"Mochila Militar"},	
	{"Mochila Livie"},		
	{"Mochila Rucksack"},		
	{"Mochila Alice"},
	{"Mochila Ossier"},
	{"Mochila Asalto"},	
	{"Mochila Coyote"},
	{"Mochila Krysset"},
	{"Mochila Gamespot"},
	{"Improvised Backpack"},
	{"Schoolar Backpack"},
	{"Cabo Backpack"},
	{"Assault Light Backpack"},
	{"Guillie Backpack"},
	{"Survivor Backpack"},
	{"Camping Backpack"},
	{"Mountain Light Backpack"},
	{"Mountain Backpack"},
	{"Czech Camo Backpack"},
	{"Coyote Camo Backpack"},
	{"SFG Army Camo Backpack"},
	-- OTROS
	{"Valla de alambre"},
	{"Lata vacia"},
	{"Lata de soda vacia"},
	{"Mina"},
	{"Trampa de oso"},
	{"Mina laser"},
	{"Bidon de gasolina"},
	{"Bidon vacio"},
	{"Tienda basica"},
	{"Bengala"},
	{"Botella de agua vacia"},	
	{"Mapa"},
	{"Pila de madera"},
	{"Bolsa termica"},
	{"GPS"},
	{"Caja de herramientas"},
	{"Cerillos"},
	{"Reloj"},
	{"Trozo de metal"},
	{"VN Visor"},
	{"IR Visor"},
	{"Binoculares"},
	{"Casco de aviador"},
	{"Casco de moto"},
	{"Casco basico"},
	{"Casco de guerra"},
	{"Casco de aviador"},
	{"Chaleco de policia"},
	{"Chaleco civil"},
	{"Chaleco de guerra"},
	{"Guillie Suit"},	
	{"Survivor Suit"},
	{"Police Suit"},
	-- PARTES DE UN VEHICULO
	{"Motor"},
	{"Bateria"},
	{"Tanque de combustible"},
	{"Neumatico"},
	{"Rotador"},
	-- ALIMENTICIOS
	{"Doritos"},
	{"Botella de agua"},
	{"Frijoles"},
	{"Pasta"},
	{"Sardinas"},
	{"Salchichas"},
	{"MRE"},
	{"Maiz"},
	{"Guisantes"},
	{"Estofado"},
	{"Puerco"},
	{"Frutas"},
	{"Estofado de pescado"},
	{"Ravioles"},
	{"Leche"},
	{"Carne cocinada"},
	{"Carne cruda"},
	{"Cola"},
	{"Dew"},
	{"Pepsi"},
}