hotBarItems = {
	["Analgésicos"] = true,
	["Antibioticos"] = true,
	["Morfina"] = true,
	["Kit de Primeiros Socorros"] = true,
	["Curativo"] = true,
	["Bolsa de Sangue"] = true,
	["Transfusor de Sangue"] = true,
	["Bolsa Térmica"] = true,
	["Esteróides"] = true,
	["Garrafa de Água"] = true,
	["Doritos"] = true,
	["Feijões Enlatados"] = true,
	["Macarrão Enlatado"] = true,
	["Sardinhas Enlatadas"] = true,
	["Salchichas Enlatadas"] = true,
	["Ração Militar"] = true,
	["Milho Enlatado"] = true,
	["Ervilhas Enlatadas"] = true,
	["Sopa Enlatada"] = true,
	["Porco Enlatado"] = true,
	["Frutas Enlatadas"] = true,
	["Sopa de Peixe"] = true,
	["Ravioles Enlatados"] = true,
	["Leite"] = true,
	["Carne Cozida"] = true,
	["Carne Crua"] = true,
	["Coca-Cola"] = true,
	["Mountain Dew"] = true,
	["Pepsi"] = true,
	["Bengala"] = true,
	["Bateria"] = true,
	["Garrafa de Água vacia"] = true,
	--["Tienda basica"] = true,
	--["Mina"] = true,
	--["Armadilha para Urso"] = true,
	["PGM Hecate"] = true,
	["Winchester 1866"] = true,
	["CZ 550"] = true,
	["Dragunov"] = true,
	["G28"] = true,
	["Barret 50"] = true,
	["M107"] = true,
	["Mk14-EBR"] = true,
	["AS50"] = true,
	["PKM"] = true,
	["Mk-48"] = true,
	["AKS Gold"] = true,
	["AK-74 PSO"] = true,
	["AKS-74UN Kobra"] = true,
	["IMI Galil"] = true,
	["AK-74"] = true,
	["G36C"] = true,
	["FN FNC"] = true,
	["ACR"] = true,
	["FN FAL"] = true,
	["M16"] = true,
	["Steyr AUG"] = true,
	["M4A3 CCO"] = true,
	["Ballesta"] = true,
	["Benelli"] = true,
	["Remington 870"] = true,
	["Bizon PP-19 SD"] = true,
	["MP5A5"] = true,
	["Palanca"] = true,
	["Machado"] = true,
	["USP45 SD"] = true,
	["Beretta M92F"] = true,
	["Desert Eagle"] = true,
	["USP45"] = true,
	["M9"] = true,
	["PDW"] = true,
	["M1911"] = true,
	["Revolver"] = true,
	["Cuchillo"] = true,
	["Granada"] = true,
	["Paraquedas"] = true,
	["Binóculos"] = true,
	["Improvised Backpack"] = true,
	["Schoolar Backpack"] = true,
	["Cabo Backpack"] = true,
	["Assault Light Backpack"] = true,
	["Guillie Backpack"] = true,
	["Survivor Backpack"] = true,
	["Camping Backpack"] = true,
	["Mountain Light Backpack"] = true,
	["Mountain Backpack"] = true,
	["Czech Camo Backpack"] = true,
	["Coyote Camo Backpack"] = true,
	["SFG Army Backpack"] = true,
	["Mochila Coyote"] = true,
	["Mochila Krysset"] = true,
	["Mochila Militar"] = true,
	["Mochila Livie"] = true,
	["Mochila Rucksack"] = true,
	["Mochila Alice"] = true,
	["Mochila Ossier"] = true,
	["Mochila Asalto"] = true,
	["Mochila Gamespot"] = true,
	["Bengala"] = true,
	["Casco de moto"] = true,
	["Casco basico"] = true,
	["Casco de guerra"] = true,
	["Casco de aviador"] = true,
	["Chaleco de policia"] = true,
	["Chaleco civil"] = true,
	["Chaleco de guerra"] = true,
	["Chaleco basico"] = true,
}

gearTable = {
	["Primary Weapons"] = {
		{"PGM Hecate", "hecate.png", 76, 38, "Francotirador potente que quita 12500 de daño.", "PGM Hecate"},
		{"Winchester 1866", "winchester.png", 76, 38, "Rifle antiguo que quita 10593 de daño.", "Winchester 1866"},
		{"CZ 550", "cz550.png", 76, 38, "Rifle de caceria que quita 11096 de daño.", "CZ550"},	
		{"Dragunov", "dragunov.png", 76, 38, "Francotirador de cuerpo a tierra que quita 9496 de daño.", "SVD Dragunov"},
		{"Barret 50", "barret50.png", 76, 38, "Francotirador reforzado que quita 12596 de daño.", "Barret 50"},
		{"G28", "g28.png", 76, 38, "Francotirador de precision que quita hasta 11596 de daño.", "G28"},
		{"M107", "m107.png", 76, 38, "Francotirador de precision que quita hasta 10499 de daño.", "M107"},
		{"Mk14-EBR", "mk14.png", 76, 38, "Francotirador personalizado que quita alrededor de 11980 de daño.", "Mk14 EBR"},
		{"AS50", "as50.png", 76, 38, "Francotirador potente que quita 12196 de daño.", "AS50"},
		{"M79", "m79.png", 76, 38, "Cargador: Proyectil M203 \nTamaño del cargador: Unico disparo", "M4A1 M203"},	

		{"PKM", "pkm.png", 76, 38, "Ametralladora automatica que quita 5269 de daño.", "PKM"},
		{"Mk-48", "mk48.png", 76, 38, "Ametralladora automatica que quita 5496 de daño.", "Mk 48"},
	
		{"AKS Gold", "aksgold.png", 76, 38, "Una hermosa arma bañada en oro que quita 5296 de daño.", "AKS Gold"},
		{"AK-74 PSO", "akpso.png", 76, 38, "AK-74 con una mira PSO que quita 4469 de daño.", "AK-74 PSO"},
		{"AKS-74UN Kobra", "akskobra.png", 76, 38, "AK-74 modificada que quita 4469 de daño", "AKS-74UN Kobra"},
		{"IMI Galil", "galil.png", 76, 38, "La Galil es un arma preferida por las guerrillas que quita 4296 de daño.", "IMI Galil"},
		{"AK-74", "ak74.png", 76, 38, "La AK-74 es una version mas pesado que la AK-74. Quita 4469 de daño.", "AK-74"},

		{"G36C", "g36c.png", 76, 38, "Rifle de asalto que quita 4576 de daño.", "G36C"},
		{"FN FNC", "fnfnc.png", 76, 38, "Es una version mas moderna de la FN FAL que quita 4576 de daño.", "FN FNC"},		
		{"ACR", "acr.png", 76, 38, "Rifle de asalto tactico que quita 4963 de daño.", "ACR"},
		{"FN FAL", "fnfal.png", 76, 38, "Rifle de asalto tactico que quita 4576 de daño.", "FN FAL"},
		{"M16", "m16.png", 76, 38, "Rifle de asalto tactico que quita 4796 de daño.", "M16"},
		{"Steyr AUG", "aug.png", 76, 38, "Rifle semi-automatico que quita 5196 de daño.", "Steyr AUG"},
		{"M4A3 CCO", "m4a3cco.png", 76, 38, "Rifle semi-automatico que quita 4096 de daño.", "M4A3 CCO"},

		{"Ballesta", "crossbow.png", 76, 38, "Puedes usar la ballesta con las flechas.", "Ballesta"},

		{"Benelli", "benelli.png", 76, 38, "Escopeta Benelli. Quita 8991 de daño.", "Benelli"},
		{"Remington 870", "remington.png", 76, 38, "Escopeta de la serie Remington que quita 8800 de daño.", "Remington 870"},
	},
	["Secondary Weapons"] = {
		{"Bizon PP-19 SD", "bizon.png", 76, 38, "Fusil semi-automatico que quita 5396 de daño.", "Bizon PP-19 SD"},
		{"MP5A5", "mp5a5.png", 76, 38, "Fusil semi-automatico que quita 5342 de daño.", "MP5A5"},
		{"Palanca", "crowbar.png", 76, 38, "Puede ser utilizado para golpear.", "Palanca"},	
		{ "Machado", "axe.png", 76, 38, "Você pode cortar árvores se acertá-las", "Machado" },
		{"USP45 SD", "usp45sd.png",76, 38, "El arma preferida por los militares. Quita 7896 de daño.", "USP45 SD"},
		{"Beretta M92F", "beretta30.png",38, 38, "Un arma poco comun que quita 8693 de daño.", "Beretta M92F"},
		{"Desert Eagle", "deagle.png",38, 38, "Es una potente arma que quita 7769 de daño.", "Desert Eagle"},
		{"USP45", "usp45.png",38, 38, "El arma preferida por los militares. Quita 7896 de daño.", "USP45"},	
		{"M9", "m9.png",38, 38, "Es un arma de la serie Beretta que quita 6769 de daño.", "M9"},
		{"PDW", "pdw.png",38, 38, "Fusil semi-automatico que quita 5796 de daño.", "PDW"},
		{"M1911", "m1911a1.png",38, 38, "Es un arma precisa que quita 7369 de daño.", "M1911"},
		{"Revolver", "revolver.png",38, 38, "Es un Revolver Colt que quita 7769 de daño.", "Revolver"},
		{"Cuchillo", "knife.png", 38, 38, "Puede ser utilizado para defensa y para cortar carne de animales.", "Cuchillo"},	
	},
	["Ammo"] = {
		{"Flecha", "arrow.png",38, 38, "Municion compatible con la Ballesta.", "Flecha"},
		{"12 Gauge", "shotgun.png",38, 38, "Municion compatible con Benelli, Remington 870.", "12 Gauge"},
		{"5.45x39mm", "ak.png",38, 38, "Municion compatible con AK-74 PSO, AK-74, AKS-74UN Kobra, IMI Galil, AKS Gold.", "5.45x39mm RND"},
		{"5.56x45mm", "m4mag.png",38, 38, "Municion compatible con M16, ACR, FN FAL, FN FNC, M4A1 M203, Steyr AUG, G36C.", "5.56x45mm RND"},
		{"7.62x51mm", "british.png",38, 38, "Municion compatible con PKM, Mk-48.", "7.62x51mm RND"},
		{"7.62x54mm", "sniper.png",38, 38, "Municion compatible con PGM Hecate, Barret 50, Dragunov, G28, AS50, Mk14 EBR, M107.", "7.62x54mm RND"},
		{"1866 Slug", "shotgun.png",38, 38, "Municion compatible con Winchester 1866.", "1866 Slug"},
		{"9x18mm", "9x18.png",38, 38, "Municion compatible con Beretta M92F, M9, USP45, USP45 SD.", "9x18mm RND"},
		{"9x19mm", "9x19.png",38, 38, "Municion compatible con PDW, MP5A5, Bizon PP-19 SD.", "9x19mm RND"},
		{"11.43x23mm", "45colt.png",38, 38, "Municion compatible con Revolver, M1911, Desert Eagle.", "11.43x23mm RND"},
		{".308 Winchester", "sniper.png",38, 38, "Municion compatible con CZ 550.", ".308 Winchester"},	
	},
	["Specially Weapons"] = {
		{ "Granada", "grenade.png", 38, 38, "Exploda seus inimigos de uma vez por todas!", "Granada" },	
		{ "Paraquedas", "parachute.png", 38, 38, "Salte sem medo algum!", "Paraquedas" },	
		{ "Binóculos", "binoculars.png", 38, 38, "Veja os lugares de longa distância.", "Binóculos" },
	},
	["Medical"] = {
		{ "Analgésicos", "painkillers.png", 38, 38, "Ajuda a tratar dores.", "Analgésicos" },
		{ "Antibioticos", "antibiotics.png", 38, 38, "Ajuda a tratar infecções.", "Antibioticos" },
		{ "Morfina", "morphine.png", 38, 38, "Ajuda a tratar ossos quebrados.", "Morfina" },
		{ "Kit de Primeiros Socorros", "first-aid-kit.png", 38, 38, "Regenera o seu sangue.", "Kit de Primeiros Socorros" },
		{ "Curativo", "bandage.png", 38, 38, "Ajuda a parar o sangramento.", "Curativo" },
		{ "Bolsa de Sangue", "bloodbag.png", 38, 38, "Bolsa de sangue para transfusões", "Bolsa de Sangue" },
		{ "Transfusor de Sangue", "transfusion.png", 38, 38, "Permite transfusões de sangue.", "Transfusor de Sangue" },
		{ "Bolsa Térmica", "heatpack.png", 38, 38, "Ajuda a tratar a hipotermia.", "Bolsa Térmica" },
		{ "Esteróides", "injection.png", 38, 38, "Aumenta as habilidades por um certo tempo.", "Esteróides" },
	},
	["Backpacks"] = {
		{"Improvised Backpack", "improvised.png",38, 38, "Es una mochila con 12 de espacios.", "Mochila Improvisada"},
		{"Schoolar Backpack", "schoolar.png",38, 38, "Es una mochila con 14 de espacios.", "Mochila Escolar"},
		{"Cabo Backpack", "cabo.png",38, 38, "Es una mochila con 16 de espacios.", "Mochila Cabo"},
		{"Assault Light Backpack", "assault_light.png",38, 38, "Es una mochila con 18 de espacios.", "Mochila Asalto Pequeña"},
		{"Guillie Backpack", "guillie.png",38, 38, "Es una mochila con 22 de espacios.", "Mochila de camuflaje"},
		{"Survivor Backpack", "survivor.png",38, 38, "Es una mochila con 28 de espacios.", "Mochila de sobreviviente"},
		{"Camping Backpack", "camping.png",38, 38, "Es una mochila con 34 de espacios.", "Mochila de campamento"},
		{"Mountain Light Backpack", "mountain_light.png", 38, 38, "Es una mochila con 36 de espacios.", "Mochila Montaña Pequeña"},
		{"Mountain Backpack", "mountain.png",38, 38, "Es una mochila con 38 de espacios.", "Mochila Montaña"},
		{"Czech Camo Backpack", "czech_camo.png",38, 38, "Es una mochila con 40 de espacios.", "Mochila Czech Camo"},
		{"Coyote Camo Backpack", "coyote_camo.png",38, 38, "Es una mochila con 43 de espacios.", "Mochila Coyote Camo"},
		{"SFG Army Backpack", "sfg_army.png",38, 38, "Es una mochila con 300 de espacios.", "Mochila SFG Army"},
		{"Mochila Coyote", "coyote.png",38, 38, "Es una mochila con 42 de espacios.", "Mochila Coyote"},	
		{"Mochila Krysset", "krysset.png",38, 38, "Es una mochila con 24 de espacios.", "Mochila Krysset"},	
		{"Mochila Militar", "militar.png",38, 38, "Es una mochila con 32 de espacios.", "Mochila Militar"},
		{"Mochila Livie", "livie.png",38, 38, "Es una mochila con 10 de espacios.", "Mochila Livie"},		
		{"Mochila Rucksack", "rucksack.png",38, 38, "Es una mochila con 30 de espacios.", "Mochila Rucksack"},
		{"Mochila Alice", "alice.png",38, 38, "Es una mochila con 26 de espacios.", "Mochila Alice"},
		{"Mochila Ossier", "ossier.png",38, 38, "Es una mochila con 50 de espacios.", "Mochila Ossier"},
		{"Mochila Asalto", "assault.png",38, 38, "Es una mochila con 20 de espacios.", "Mochila Asalto"},
		{"Mochila Gamespot", "gamespot.png",38, 38, "Es una mochila con 8 de espacios.", "Mochila Gamespot"},
	},
	["Shields"] = {
		{"Casco de moto", "helmet_moto.png",38, 38, "Te protege de los disparos en la cabeza.", "Casco de moto"},
		{"Casco basico", "helmet_basic.png",38, 38, "Te protege de los disparos en la cabeza.", "Casco basico"},
		{"Casco de guerra", "helmet_war.png",38, 38, "Te protege de los disparos en la cabeza.", "Casco de guerra"},
		{"Casco de aviador", "helmet_aviator.png",38, 38, "Te protege de los disparos en la cabeza.", "Casco de aviador"},
		{"Chaleco de policia", "armor_police.png",38, 38, "Disminuye el daño del arma.", "Chaleco de policia"},
		{"Chaleco civil", "armor_civic.png",38, 38, "Disminuye el daño del arma.", "Chaleco civil"},
		{"Chaleco de guerra", "armor_war.png",38, 38, "Disminuye el daño del arma.", "Chaleco de guerra"},
		{"Chaleco basico", "armor_basic.png",38, 38, "Disminuye el daño del arma.", "Chaleco basico"},
	},
	["Nutrition"] = {
		{ "Garrafa de Água", "waterbottle.png",38, 38, "Tá com sede? Beba-me.", "Garrafa de Água" },
		{ "Doritos", "doritos.png", 38, 38, "Um saco de doritos delicioso.", "Doritos" },
		{ "Feijões Enlatados", "bakedbeans.png", 38, 38, "Uma delicia de feijões.", "Feijões Enlatados" },
		{ "Macarrão Enlatado", "spaguetti.png", 38, 38, "Mate sua fome com este macarrão delicioso.", "Macarrão Enlatado" },
		{ "Sardinhas Enlatadas", "sardines.png", 38, 38, "Do mar para sua boca.", "Sardinhas Enlatadas" },
		{ "Salchichas Enlatadas", "frankbeans.png", 38, 38, "Hmmm que delicia.", "Salchichas Enlatadas" },
		{ "Ração Militar", "mre.png", 38, 38, "Comida para você sobreviver.", "Ração Militar" },
		{ "Milho Enlatado", "corn.png", 38, 38, "Direto da roça para sua mesa.", "Milho Enlatado" },
		{ "Ervilhas Enlatadas", "peas.png", 38, 38, "Coma ou morra de fome.", "Ervilhas Enlatadas" },
		{ "Sopa Enlatada", "stew.png", 38, 38, "Sopinha deliciosa hmmm.", "Sopa Enlatada" },
		{ "Porco Enlatado", "pork.png", 38, 38, "Olha o porco roonk!", "Porco Enlatado" },
		{ "Frutas Enlatadas", "fruit.png", 38, 38, "Frutinhas doces que nem mel.", "Frutas Enlatadas" },
		{ "Sopa de Peixe", "chowder.png", 38, 38, "Do fundo do mar para sua mesa.", "Sopa de Peixe" },
		{ "Ravioles Enlatados", "ravioli.png", 38, 38, "Uma deliciosa lata de ravioles.", "Ravioles Enlatados" },
		{ "Leite", "milkcan.png",38, 38, "Branco igual a via lactea.", "Leite" },
		{ "Carne Cozida", "coockedmeat.png", 38, 38, "Pedaço de carne cozida.", "Carne Cozida" },
		{ "Carne Crua", "rawmeat.png", 38, 38, "Pedaço de carne crua. Asse antes de comer!", "Carne Crua" },
		{ "Coca-Cola", "cola.png", 38, 38, "Lata de Coca-Cola.", "Coca-Cola" },
		{ "Mountain Dew", "dew.png", 38, 38, "Lata de Mountain Dew.", "Mountain Dew" },
		{ "Pepsi", "pepsi.png", 38, 38, "Lata de Pepsi.", "Pepsi" },
	},
	["Toolbelt"] = {
		{ "Bússola", "compass.png", 38, 38, "Uma bússola é muito importante para a sobrevivência. Saiba a direção correta.", "Bússola" },
		{ "GPS", "gps.png", 38, 38, "É um dispositivo que ajuda você a saber sua localização.", "GPS" },
		{ "Relógio", "watch.png", 38, 38, "Saiba o horário em San Andreas.", "Relógio" },
		{ "Caixa de Ferramentas", "toolbox.png", 38, 38, "Remove bloqueios e repara veículos danificados.", "Caixa de Ferramentas" },
		{ "Mapa", "map.png", 38, 38, "Mapa de San Andreas. Pressione 'F11' para ver o mapa.", "Mapa" },
		{ "Caixa de Fósforo", "matchbox.png", 38, 38, "Pode ser usado para acender fogueiras.", "Caixa de Fósforo" },
		{ "Óculos de Visão Noturna", "nvgoggles.png", 38, 38, "Pressione 'N' para ativar a visão noturna.", "Óculos de Visão Noturna" },
		{ "Óculos de Visão Termal", "nvgoggles.png", 38, 38, "Pressione 'I' para ativar a visão termal.", "Óculos de Visão Termal" },
	},
	["Others"] = {
		{ "Cerca de Arame", "wirefence.png", 38, 38, "Utilize a cerca para criar bloqueios.", "Cerca de Arame" },
		{"Guillie Suit", "clothing.png",38, 38, "Puedes usar este traje para camuflajearte en los arboles.", "Traje de camuflaje"},
		{"Survivor Suit", "clothing.png",38, 38, "Traje de supervivencia.", "Traje de sobreviviente"},
		{"Police Suit", "clothing.png",38, 38, "Traje de policia de Los Santos.", "Traje de policia"},
		{"Veterano Suit", "clothing.png",38, 38, "Traje de policia de Los Santos.", "Traje de veterano"},
		{"Camo Suit", "clothing.png",38, 38, "Traje de policia de Los Santos.", "Traje camo"},
		{"Bengala", "flare.png",38, 38, "Se utiliza para iluminar zonas con poca luz.", "Bengala"},
		{"Bateria", "battery.png",38, 38, "Bateria de un vehiculo.", "Bateria"},
		{"Bidon de gasolina", "biofuel.png",38, 38, "Bidon con gasolina.", "Bidon de gasolina"},
		{"Bidon vacio", "biofuel.png",38, 38, "Bidon sin gasolina.", "Bidon"},
		{"Motor", "engine.png",38, 38, "Es un motor para un vehiculo.", "Motor"},
		{"Garrafa de Água vacia", "emptybottle.png",38, 38, "Garrafa de Água vacia.", "Garrafa de Água vacia"},
		{"Neumatico", "tire.png",38, 38, "Es un neumatico para un vehiculo.", "Neumatico"},
		{"Pila de madera", "woodpile.png",38, 38, "Puedes hacer fogatas.", "Pila de madera"},
		{"Tienda basica", "tent.png",38, 38, "Puedes guardar tus objetos en una tienda para mas seguridad. Espacio: 250", "Carpa pequeña"},
		{"Trozo de metal", "metal.png",38, 38, "Trozo de metal viejo.", "Trozo de metal"},
		{"Lata vacia", "trashtincan.png",38, 38, "Lata de alimentos.", "Lata vacia"},
		{"Lata de soda vacia", "emptysoda.png",38, 38, "Lata de soda vacia.", "Lata de soda vacia"},
		{"Tanque de combustible", "fueltank.png",38, 38, "Es un tanque de combustible para un vehiculo.", "Tanque de combustible"},
		{"Rotador", "rotary.png",38, 38, "Rotador de un helicoptero.", "Rotador"},
		{ "Mina", "mine.png",38, 38, "Plante e exploda seus inimigos.", "Mina" },
		{ "Armadilha para Urso", "beartramp.png", 38, 38, "Use para montar armadilhas.", "Armadilha para Urso" },
	},
}