--[[
    @author: psychol.
    @mail: nezymr69@gmail.com
    @project: Pixel (MTA)
]]

CLOTHES = {}
CLOTHES.OPTIONS = {
	["Męskie"] = {
                {id=0, cost=0, level=1},
                {id=1, cost=0, level=1},
                {id=2, cost=0, level=1},
                {id=7, cost=0, level=1},
                {id=14, cost=0, level=1},
                {id=15, cost=0, level=1},
                {id=17, cost=0, level=1},
                {id=18, cost=0, level=1},
                {id=19, cost=0, level=1},
                {id=21, cost=0, level=1},
                {id=23, cost=0, level=1},
                {id=24, cost=0, level=1},
                {id=25, cost=0, level=1},
                {id=28, cost=0, level=1},
                {id=29, cost=0, level=1},
                {id=30, cost=0, level=1},
                {id=32, cost=0, level=1},
                {id=33, cost=0, level=1},
                {id=34, cost=0, level=1},
                {id=35, cost=0, level=1},
                {id=36, cost=0, level=1},
                {id=37, cost=0, level=1},
                {id=43, cost=0, level=1},
                {id=44, cost=0, level=1},
                {id=45, cost=0, level=1},
                {id=46, cost=0, level=1},
                {id=47, cost=0, level=1},
                {id=49, cost=0, level=1},
                {id=51, cost=0, level=1},
                {id=52, cost=0, level=1},
                {id=57, cost=0, level=1},
                {id=58, cost=0, level=1},
                {id=59, cost=0, level=1},
                {id=60, cost=0, level=1},
                {id=62, cost=0, level=1},
                {id=66, cost=0, level=1},
                {id=68, cost=0, level=1},
                {id=72, cost=0, level=1},
                {id=73, cost=0, level=1},
                {id=78, cost=0, level=1},
                {id=79, cost=0, level=1},
                {id=80, cost=0, level=1},
                {id=81, cost=0, level=1},
                {id=82, cost=0, level=1},
                {id=83, cost=0, level=1},
                {id=84, cost=0, level=1},
                {id=94, cost=0, level=1},
                {id=95, cost=0, level=1},
                {id=96, cost=0, level=1},
                {id=97, cost=0, level=1},
                {id=98, cost=0, level=1},
                {id=100, cost=0, level=1},
                {id=101, cost=0, level=1},
                {id=105, cost=0, level=1},
                {id=107, cost=0, level=1},
                {id=108, cost=0, level=1},
                {id=109, cost=0, level=1},
                {id=110, cost=0, level=1},
                {id=111, cost=0, level=1},
                {id=112, cost=0, level=1},
                {id=113, cost=0, level=1},
                {id=114, cost=0, level=1},
                {id=115, cost=0, level=1},
                {id=116, cost=0, level=1},
                {id=118, cost=0, level=1},
                {id=120, cost=0, level=1},
                {id=121, cost=0, level=1},
                {id=123, cost=0, level=1},
                {id=124, cost=0, level=1},
                {id=125, cost=0, level=1},
                {id=126, cost=0, level=1},
                {id=127, cost=0, level=1},
                {id=132, cost=0, level=1},
                {id=133, cost=0, level=1},
                {id=134, cost=0, level=1},
                {id=135, cost=0, level=1},
                {id=136, cost=0, level=1},
                {id=137, cost=0, level=1},
                {id=142, cost=0, level=1},
                {id=143, cost=0, level=1},
                {id=144, cost=0, level=1},
                {id=146, cost=0, level=1},
                {id=147, cost=0, level=1},
                {id=153, cost=0, level=1},
                {id=154, cost=0, level=1},
                {id=156, cost=0, level=1},
                {id=158, cost=0, level=1},
                {id=159, cost=0, level=1},
                {id=160, cost=0, level=1},
                {id=161, cost=0, level=1},
                {id=162, cost=0, level=1},
                {id=167, cost=0, level=1},
                {id=168, cost=0, level=1},
                {id=170, cost=0, level=1},
                {id=171, cost=0, level=1},
                {id=173, cost=0, level=1},
                {id=174, cost=0, level=1},
                {id=175, cost=0, level=1},
                {id=176, cost=0, level=1},
                {id=179, cost=0, level=1},
                {id=180, cost=0, level=1},
                {id=182, cost=0, level=1},
                {id=184, cost=0, level=1},
                {id=185, cost=0, level=1},
                {id=186, cost=0, level=1},
                {id=187, cost=0, level=1},
                {id=189, cost=0, level=1},
                {id=200, cost=0, level=1},
                {id=202, cost=0, level=1},
                {id=203, cost=0, level=1},
                {id=204, cost=0, level=1},
                {id=206, cost=0, level=1},
                {id=209, cost=0, level=1},
                {id=210, cost=0, level=1},
                {id=212, cost=0, level=1},
                {id=217, cost=0, level=1},
                {id=221, cost=0, level=1},
                {id=222, cost=0, level=1},
                {id=223, cost=0, level=1},
                {id=227, cost=0, level=1},
                {id=228, cost=0, level=1},
                {id=229, cost=0, level=1},
                {id=230, cost=0, level=1},
                {id=239, cost=0, level=1},
                {id=240, cost=0, level=1},
                {id=241, cost=0, level=1},
                {id=242, cost=0, level=1},
                {id=247, cost=0, level=1},
                {id=248, cost=0, level=1},
                {id=249, cost=0, level=1},
                {id=250, cost=0, level=1},
                {id=252, cost=0, level=1},
                {id=253, cost=0, level=1},
                {id=254, cost=0, level=1},
                {id=258, cost=0, level=1},
                {id=259, cost=0, level=1},
                {id=261, cost=0, level=1},
                {id=262, cost=0, level=1},
                {id=264, cost=0, level=1},
                {id=269, cost=0, level=1},
                {id=270, cost=0, level=1},
                {id=272, cost=0, level=1},
                {id=291, cost=0, level=1},
                {id=292, cost=0, level=1},
                {id=293, cost=0, level=1},
                {id=294, cost=0, level=1},
                {id=295, cost=0, level=1},
                {id=296, cost=0, level=1},
                {id=297, cost=0, level=1},
                {id=299, cost=0, level=1},
                {id=300, cost=0, level=1},
                {id=301, cost=0, level=1},
                {id=302, cost=0, level=1},
                {id=303, cost=0, level=1},
                {id=306, cost=0, level=1},
                {id=307, cost=0, level=1},
                {id=308, cost=0, level=1},
                {id=311, cost=0, level=1},
                {id=312, cost=0, level=1},
                {id=181, cost=0, level=1},
                {id=213, cost=0, level=1},
                {id=220, cost=0, level=1},
                {id=234, cost=0, level=1},
                {id=235, cost=0, level=1},
                {id=236, cost=0, level=1},
                {id=290, cost=0, level=1},
                {id=310, cost=0, level=1},
	},

	["Kobiece"] = {
                {id=11, cost=0, level=1},
                {id=12, cost=0, level=1},
                {id=13, cost=0, level=1},
                {id=31, cost=0, level=1},
                {id=38, cost=0, level=1},
                {id=40, cost=0, level=1},
                {id=41, cost=0, level=1},
                {id=53, cost=0, level=1},
                {id=54, cost=0, level=1},
                {id=55, cost=0, level=1},
                {id=56, cost=0, level=1},
                {id=63, cost=0, level=1},
                {id=64, cost=0, level=1},
                {id=69, cost=0, level=1},
                {id=75, cost=0, level=1},
                {id=76, cost=0, level=1},
                {id=77, cost=0, level=1},
                {id=85, cost=0, level=1},
                {id=88, cost=0, level=1},
                {id=89, cost=0, level=1},
                {id=90, cost=0, level=1},
                {id=91, cost=0, level=1},
                {id=92, cost=0, level=1},
                {id=129, cost=0, level=1},
                {id=130, cost=0, level=1},
                {id=131, cost=0, level=1},
                {id=138, cost=0, level=1},
                {id=140, cost=0, level=1},
                {id=141, cost=0, level=1},
                {id=148, cost=0, level=1},
                {id=150, cost=0, level=1},
                {id=151, cost=0, level=1},
                {id=152, cost=0, level=1},
                {id=157, cost=0, level=1},
                {id=169, cost=0, level=1},
                {id=172, cost=0, level=1},
                {id=178, cost=0, level=1},
                {id=190, cost=0, level=1},
                {id=192, cost=0, level=1},
                {id=193, cost=0, level=1},
                {id=194, cost=0, level=1},
                {id=195, cost=0, level=1},
                {id=196, cost=0, level=1},
                {id=197, cost=0, level=1},
                {id=198, cost=0, level=1},
                {id=199, cost=0, level=1},
                {id=201, cost=0, level=1},
                {id=205, cost=0, level=1},
                {id=207, cost=0, level=1},
                {id=214, cost=0, level=1},
                {id=215, cost=0, level=1},
                {id=216, cost=0, level=1},
                {id=218, cost=0, level=1},
                {id=219, cost=0, level=1},
                {id=224, cost=0, level=1},
                {id=225, cost=0, level=1},
                {id=231, cost=0, level=1},
                {id=232, cost=0, level=1},
                {id=233, cost=0, level=1},
                {id=237, cost=0, level=1},
                {id=238, cost=0, level=1},
                {id=245, cost=0, level=1},
                {id=251, cost=0, level=1},
                {id=256, cost=0, level=1},
                {id=263, cost=0, level=1},
                {id=298, cost=0, level=1},
                {id=39, cost=0, level=1},
                {id=304, cost=0, level=1},
                {id=93, cost=0, level=1},
	},

	["Premium"] = {
                {id=9, cost=0, level=1},
                {id=139, cost=0, level=1},
                {id=191, cost=0, level=1},
                {id=243, cost=0, level=1},
                {id=257, cost=0, level=1},
                {id=244, cost=0, level=1},
                {id=246, cost=0, level=1},
                {id=87, cost=0, level=1},
                {id=145, cost=0, level=1},
                {id=128, cost=0, level=1},
                {id=188, cost=0, level=1},
                {id=117, cost=0, level=1},
                {id=183, cost=0, level=1},
                {id=48, cost=0, level=1},
                {id=102, cost=0, level=1},
                {id=122, cost=0, level=1},
                {id=20, cost=0, level=1},
                {id=67, cost=0, level=1},
                {id=104, cost=0, level=1},
                {id=106, cost=0, level=1},
                {id=103, cost=0, level=1},
	},
}

function tableMerge(t1, t2, cat)
    for _,v in pairs(t2) do
        k=#t1+1
        v.category=cat
        if type(v) == "table" then
            if type(t1[k] or false) == "table" then
                tableMerge(t1[k] or {}, t2[k] or {})
            else
                t1[k] = v
            end
        else
            t1[k] = v
        end
    end
    return t1
end

CLOTHES.OPTIONS["Wszystkie"]={}

tableMerge(CLOTHES.OPTIONS["Wszystkie"], CLOTHES.OPTIONS["Męskie"], "Męskie")
tableMerge(CLOTHES.OPTIONS["Wszystkie"], CLOTHES.OPTIONS["Kobiece"], "Kobiece")
tableMerge(CLOTHES.OPTIONS["Wszystkie"], CLOTHES.OPTIONS["Premium"], "Premium")

for i,v in pairs(CLOTHES.OPTIONS) do
    table.sort(CLOTHES.OPTIONS[i], function(a,b) return a.id < b.id end)
end

--[[function loadSkinPrev(id)
    local skin=createPed(id, 0, 0, 0)
    local prev=exports.object_preview:createObjectPreview(skin, 0, 0, 180, 0, 0, 200, 200, false, true, true)
    setTimer(function()
        exports.object_preview:saveRTToFile(prev, "skins/"..id..".png")
        destroyElement(skin)
    end, 500, 1)
end

for i,v in pairs(CLOTHES.OPTIONS["Wszystkie"]) do
    setTimer(function()
        loadSkinPrev(v.id)
    end, (750*i), 1)
end]]