----------------------
-- buildings//
----------------------

txd = engineLoadTXD("tex/buildings/1.txd", 2290 )
engineImportTXD(txd, 2290)
dff = engineLoadDFF("tex/buildings/1.dff", 2290 )
engineReplaceModel(dff, 2290)
col = engineLoadCOL("tex/buildings/1.col", 2290 )
engineReplaceCOL (col, 2290)
txd = engineLoadTXD("tex/buildings/2.txd", 16356 )
engineImportTXD(txd, 16356)
dff = engineLoadDFF("tex/buildings/2.dff", 16356 )
engineReplaceModel(dff, 16356)
col = engineLoadCOL("tex/buildings/2.col", 16356 )
engineReplaceCOL (col, 16356)
txd = engineLoadTXD("tex/buildings/3.txd", 17925 )
engineImportTXD(txd, 17925)
dff = engineLoadDFF("tex/buildings/3.dff", 17925 )
engineReplaceModel(dff, 17925)
col = engineLoadCOL("tex/buildings/3.col", 17925 )
engineReplaceCOL (col, 17925)
txd = engineLoadTXD("tex/buildings/4.txd", 16338 )
engineImportTXD(txd, 16338)
dff = engineLoadDFF("tex/buildings/4.dff", 16338 )
engineReplaceModel(dff, 16338)
col = engineLoadCOL("tex/buildings/4.col", 16338 )
engineReplaceCOL (col, 16338)
txd = engineLoadTXD("tex/buildings/5.txd", 16339 )
engineImportTXD(txd, 16339)
dff = engineLoadDFF("tex/buildings/5.dff", 16339 )
engineReplaceModel(dff, 16339)
col = engineLoadCOL("tex/buildings/5.col", 16339 )
engineReplaceCOL (col, 16339)
txd = engineLoadTXD("tex/buildings/6.txd", 16355 )
engineImportTXD(txd, 16355)
dff = engineLoadDFF("tex/buildings/6.dff", 16355 )
engineReplaceModel(dff, 16355)
col = engineLoadCOL("tex/buildings/6.col", 16355 )
engineReplaceCOL (col, 16355)
txd = engineLoadTXD("tex/buildings/7.txd", 3922 )
engineImportTXD(txd, 3922)
dff = engineLoadDFF("tex/buildings/7.dff", 3922 )
engineReplaceModel(dff, 3922)
col = engineLoadCOL("tex/buildings/7.col", 3922 )
engineReplaceCOL (col, 3922)
txd = engineLoadTXD("tex/buildings/8.txd", 3921 )
engineImportTXD(txd, 3921)
dff = engineLoadDFF("tex/buildings/8.dff", 3921 )
engineReplaceModel(dff, 3921)
col = engineLoadCOL("tex/buildings/8.col", 3921 )
engineReplaceCOL (col, 3921)
txd = engineLoadTXD("tex/buildings/9.txd", 14603 )
engineImportTXD(txd, 14603)
dff = engineLoadDFF("tex/buildings/9.dff", 14603 )
engineReplaceModel(dff, 14603)
col = engineLoadCOL("tex/buildings/9.col", 14603 )
engineReplaceCOL (col, 14603)
txd = engineLoadTXD("tex/buildings/10.txd", 14814 )
engineImportTXD(txd, 14814)
dff = engineLoadDFF("tex/buildings/10.dff", 14814 )
engineReplaceModel(dff, 14814)
col = engineLoadCOL("tex/buildings/10.col", 14814 )
engineReplaceCOL (col, 14814)
txd = engineLoadTXD("tex/buildings/11.txd", 3919 )
engineImportTXD(txd, 3919)
dff = engineLoadDFF("tex/buildings/11.dff", 3919 )
engineReplaceModel(dff, 3919)

col = engineLoadCOL("tex/buildings/11.col", 3919 )
engineReplaceCOL (col, 3919)


txd = engineLoadTXD("tex/buildings/12.txd", 16350 )
engineImportTXD(txd, 16350)

dff = engineLoadDFF("tex/buildings/12.dff", 16350 )
engineReplaceModel(dff, 16350)

col = engineLoadCOL("tex/buildings/12.col", 16350 )
engineReplaceCOL (col, 16350)


txd = engineLoadTXD("tex/buildings/13.txd", 2617 )
engineImportTXD(txd, 2617)

dff = engineLoadDFF("tex/buildings/13.dff", 2617 )
engineReplaceModel(dff, 2617)

col = engineLoadCOL("tex/buildings/13.col", 2617 )
engineReplaceCOL (col, 2617)


txd = engineLoadTXD("tex/buildings/14.txd", 2894 )
engineImportTXD(txd, 2894)

dff = engineLoadDFF("tex/buildings/14.dff", 2894 )
engineReplaceModel(dff, 2894)

col = engineLoadCOL("tex/buildings/14.col", 2894 )
engineReplaceCOL (col, 2894)


txd = engineLoadTXD("tex/buildings/15.txd", 2114 )
engineImportTXD(txd, 2114)

dff = engineLoadDFF("tex/buildings/15.dff", 2114 )
engineReplaceModel(dff, 2114)

col = engineLoadCOL("tex/buildings/15.col", 2114 )
engineReplaceCOL (col, 2114)


txd = engineLoadTXD("tex/buildings/16.txd", 2274 )
engineImportTXD(txd, 2274)

dff = engineLoadDFF("tex/buildings/16.dff", 2274 )
engineReplaceModel(dff, 2274)

col = engineLoadCOL("tex/buildings/16.col", 2274 )
engineReplaceCOL (col, 2274)


txd = engineLoadTXD("tex/buildings/17.txd", 2740 )
engineImportTXD(txd, 2740)

dff = engineLoadDFF("tex/buildings/17.dff", 2740 )
engineReplaceModel(dff, 2740)

col = engineLoadCOL("tex/buildings/17.col", 2740 )
engineReplaceCOL (col, 2740)


txd = engineLoadTXD("tex/buildings/18.txd", 2707 )
engineImportTXD(txd, 2707)

dff = engineLoadDFF("tex/buildings/18.dff", 2707 )
engineReplaceModel(dff, 2707)

col = engineLoadCOL("tex/buildings/18.col", 2707 )
engineReplaceCOL (col, 2707)

txd = engineLoadTXD("tex/buildings/19.txd", 2572 )
engineImportTXD(txd, 2572)
dff = engineLoadDFF("tex/buildings/19.dff", 2572 )
engineReplaceModel(dff, 2572)
col = engineLoadCOL("tex/buildings/19.col", 2572 )
engineReplaceCOL (col, 2572)

txd = engineLoadTXD("tex/buildings/20.txd", 1921 )
engineImportTXD(txd, 1921)

dff = engineLoadDFF("tex/buildings/20.dff", 1921 )
engineReplaceModel(dff, 1921)

col = engineLoadCOL("tex/buildings/20.col", 1921 )
engineReplaceCOL (col, 1921)


txd = engineLoadTXD("tex/buildings/21.txd", 2882 )
engineImportTXD(txd, 2882)

dff = engineLoadDFF("tex/buildings/21.dff", 2882 )
engineReplaceModel(dff, 2882)

col = engineLoadCOL("tex/buildings/21.col", 2882 )
engineReplaceCOL (col, 2882)


txd = engineLoadTXD("tex/buildings/22.txd", 2825 )
engineImportTXD(txd, 2825)

dff = engineLoadDFF("tex/buildings/22.dff", 2825 )
engineReplaceModel(dff, 2825)

col = engineLoadCOL("tex/buildings/22.col", 2825 )
engineReplaceCOL (col, 2825)


txd = engineLoadTXD("tex/buildings/23.txd", 2357 )
engineImportTXD(txd, 2357)

dff = engineLoadDFF("tex/buildings/23.dff", 2357 )
engineReplaceModel(dff, 2357)

col = engineLoadCOL("tex/buildings/23.col", 2357 )
engineReplaceCOL (col, 2357)


txd = engineLoadTXD("tex/buildings/24.txd", 2289 )
engineImportTXD(txd, 2289)

dff = engineLoadDFF("tex/buildings/24.dff", 2289 )
engineReplaceModel(dff, 2289)

col = engineLoadCOL("tex/buildings/24.col", 2289 )
engineReplaceCOL (col, 2289)


txd = engineLoadTXD("tex/buildings/25.txd", 2288 )
engineImportTXD(txd, 2288)

dff = engineLoadDFF("tex/buildings/25.dff", 2288 )
engineReplaceModel(dff, 2288)

col = engineLoadCOL("tex/buildings/25.col", 2288 )
engineReplaceCOL (col, 2288)


txd = engineLoadTXD("tex/buildings/26.txd", 2287 )
engineImportTXD(txd, 2287)

dff = engineLoadDFF("tex/buildings/26.dff", 2287 )
engineReplaceModel(dff, 2287)

col = engineLoadCOL("tex/buildings/26.col", 2287 )
engineReplaceCOL (col, 2287)


txd = engineLoadTXD("tex/buildings/27.txd", 1920 )
engineImportTXD(txd, 1920)

dff = engineLoadDFF("tex/buildings/27.dff", 1920 )
engineReplaceModel(dff, 1920)

col = engineLoadCOL("tex/buildings/27.col", 1920 )
engineReplaceCOL (col, 1920)


txd = engineLoadTXD("tex/buildings/28.txd", 2285 )
engineImportTXD(txd, 2285)

dff = engineLoadDFF("tex/buildings/28.dff", 2285 )
engineReplaceModel(dff, 2285)

col = engineLoadCOL("tex/buildings/28.col", 2285 )
engineReplaceCOL (col, 2285)


txd = engineLoadTXD("tex/buildings/29.txd", 2284 )
engineImportTXD(txd, 2284)

dff = engineLoadDFF("tex/buildings/29.dff", 2284 )
engineReplaceModel(dff, 2284)

col = engineLoadCOL("tex/buildings/29.col", 2284 )
engineReplaceCOL (col, 2284)


txd = engineLoadTXD("tex/buildings/30.txd", 2283 )
engineImportTXD(txd, 2283)

dff = engineLoadDFF("tex/buildings/30.dff", 2283 )
engineReplaceModel(dff, 2283)

col = engineLoadCOL("tex/buildings/30.col", 2283 )
engineReplaceCOL (col, 2283)


txd = engineLoadTXD("tex/buildings/31.txd", 2282 )
engineImportTXD(txd, 2282)

dff = engineLoadDFF("tex/buildings/31.dff", 2282 )
engineReplaceModel(dff, 2282)

col = engineLoadCOL("tex/buildings/31.col", 2282 )
engineReplaceCOL (col, 2282)


txd = engineLoadTXD("tex/buildings/32.txd", 2281 )
engineImportTXD(txd, 2281)

dff = engineLoadDFF("tex/buildings/32.dff", 2281 )
engineReplaceModel(dff, 2281)

col = engineLoadCOL("tex/buildings/32.col", 2281 )
engineReplaceCOL (col, 2281)


txd = engineLoadTXD("tex/buildings/33.txd", 2280 )
engineImportTXD(txd, 2280)

dff = engineLoadDFF("tex/buildings/33.dff", 2280 )
engineReplaceModel(dff, 2280)

col = engineLoadCOL("tex/buildings/33.col", 2280 )
engineReplaceCOL (col, 2280)


txd = engineLoadTXD("tex/buildings/34.txd", 2279 )
engineImportTXD(txd, 2279)

dff = engineLoadDFF("tex/buildings/34.dff", 2279 )
engineReplaceModel(dff, 2279)

col = engineLoadCOL("tex/buildings/34.col", 2279 )
engineReplaceCOL (col, 2279)


txd = engineLoadTXD("tex/buildings/35.txd", 2278 )
engineImportTXD(txd, 2278)

dff = engineLoadDFF("tex/buildings/35.dff", 2278 )
engineReplaceModel(dff, 2278)

col = engineLoadCOL("tex/buildings/35.col", 2278 )
engineReplaceCOL (col, 2278)


txd = engineLoadTXD("tex/buildings/36.txd", 2277 )
engineImportTXD(txd, 2277)

dff = engineLoadDFF("tex/buildings/36.dff", 2277 )
engineReplaceModel(dff, 2277)

col = engineLoadCOL("tex/buildings/36.col", 2277 )
engineReplaceCOL (col, 2277)


txd = engineLoadTXD("tex/buildings/37.txd", 2276 )
engineImportTXD(txd, 2276)

dff = engineLoadDFF("tex/buildings/37.dff", 2276 )
engineReplaceModel(dff, 2276)

col = engineLoadCOL("tex/buildings/37.col", 2276 )
engineReplaceCOL (col, 2276)


txd = engineLoadTXD("tex/buildings/38.txd", 2275 )
engineImportTXD(txd, 2275)

dff = engineLoadDFF("tex/buildings/38.dff", 2275 )
engineReplaceModel(dff, 2275)

col = engineLoadCOL("tex/buildings/38.col", 2275 )
engineReplaceCOL (col, 2275)


txd = engineLoadTXD("tex/buildings/39.txd", 1857 )
engineImportTXD(txd, 1857)

dff = engineLoadDFF("tex/buildings/39.dff", 1857 )
engineReplaceModel(dff, 1857)

col = engineLoadCOL("tex/buildings/39.col", 1857 )
engineReplaceCOL (col, 1857)



txd = engineLoadTXD("tex/buildings/A51_jetdoor.txd", 3095 )
engineImportTXD(txd, 3095)
txd = engineLoadTXD("tex/buildings/Cartel.txd", 9131 )
engineImportTXD(txd, 9131)
dff = engineLoadDFF("tex/buildings/Cartel.dff", 9131 )
engineReplaceModel(dff, 9131)
col = engineLoadCOL("tex/buildings/Cartel.col", 9131 )
engineReplaceCOL (col, 9131)
txd = engineLoadTXD("tex/buildings/CM.txd", 14471 )
engineImportTXD(txd, 14471)
dff = engineLoadDFF("tex/buildings/CM.dff", 14471 )
engineReplaceModel(dff, 14471)
col = engineLoadCOL("tex/buildings/CM.col", 14471 )
engineReplaceCOL (col, 14471)
txd = engineLoadTXD("tex/buildings/CM.txd", 14476 )
engineImportTXD(txd, 14476)
dff = engineLoadDFF("tex/buildings/CM2.dff", 14476 )
engineReplaceModel(dff, 14476)
col = engineLoadCOL("tex/buildings/CM2.col", 14476 )
engineReplaceCOL (col, 14476)
txd = engineLoadTXD("tex/buildings/CM3.txd", 14484 )
engineImportTXD(txd, 14484)
dff = engineLoadDFF("tex/buildings/CM3.dff", 14484 )
engineReplaceModel(dff, 14484)
col = engineLoadCOL("tex/buildings/CM3.col", 14484 )
engineReplaceCOL (col, 14484)
txd = engineLoadTXD("tex/buildings/CM4.txd", 14485 )
engineImportTXD(txd, 14485)
dff = engineLoadDFF("tex/buildings/CM4.dff", 14485 )
engineReplaceModel(dff, 14485)
col = engineLoadCOL("tex/buildings/CM4.col", 14485 )
engineReplaceCOL (col, 14485) 
txd = engineLoadTXD("tex/buildings/safe.txd", 1922 )
engineImportTXD(txd, 1922)
dff = engineLoadDFF("tex/buildings/safe.dff", 1922 )
engineReplaceModel(dff, 1922)
col = engineLoadCOL("tex/buildings/safe.col", 1922 )
engineReplaceCOL (col, 1922) 
txd = engineLoadTXD("tex/buildings/military_briefcase.txd", 1923 )
engineImportTXD(txd, 1923)
dff = engineLoadDFF("tex/buildings/military_briefcase.dff", 1923 )
engineReplaceModel(dff, 1923)
col = engineLoadCOL("tex/buildings/military_briefcase.col", 1923 )
engineReplaceCOL (col, 1923) 
txd = engineLoadTXD("tex/buildings/CM5.txd", 14744 )
engineImportTXD(txd, 14744)
dff = engineLoadDFF("tex/buildings/CM5.dff", 14744 )
engineReplaceModel(dff, 14744)
col = engineLoadCOL("tex/buildings/CM5.col", 14744 )
engineReplaceCOL (col, 14744)
txd = engineLoadTXD("tex/buildings/Laptop.txd", 1869 )
engineImportTXD(txd, 1869)
dff = engineLoadDFF("tex/buildings/Laptop.dff", 1869 )
engineReplaceModel(dff, 1869)
txd = engineLoadTXD("tex/buildings/Suelog.txd", 1868 )
engineImportTXD(txd, 1868)
dff = engineLoadDFF("tex/buildings/Suelog.dff", 1868 )
engineReplaceModel(dff, 1868)
col = engineLoadCOL("tex/buildings/Suelog.col", 1868 )
engineReplaceCOL (col, 1868)
txd = engineLoadTXD("tex/buildings/Asfalto.txd", 1853 )
engineImportTXD(txd, 1853)
dff = engineLoadDFF("tex/buildings/Asfalto1.dff", 1853 )
engineReplaceModel(dff, 1853)
col = engineLoadCOL("tex/buildings/Asfalto1.col", 1853 )
engineReplaceCOL (col, 1853) 
txd = engineLoadTXD("tex/buildings/Asfalto.txd", 1854 )
engineImportTXD(txd, 1854)
dff = engineLoadDFF("tex/buildings/Asfalto2.dff", 1854 )
engineReplaceModel(dff, 1854)
col = engineLoadCOL("tex/buildings/Asfalto2.col", 1854 )
engineReplaceCOL (col, 1854)
txd = engineLoadTXD("tex/buildings/tent.txd")
engineImportTXD(txd, 3243)
dff = engineLoadDFF("tex/buildings/tent.dff", 3243)
engineReplaceModel(dff, 3243)
col = engineLoadCOL("tex/buildings/tent.col")
engineReplaceCOL(col,3243)
txd = engineLoadTXD("tex/buildings/medicalbox.txd")
engineImportTXD(txd, 1871)
dff = engineLoadDFF("tex/buildings/medicalbox.dff", 1871)
engineReplaceModel(dff, 1871)
col = engineLoadCOL("tex/buildings/medicalbox.col")
engineReplaceCOL(col,1871)
txd = engineLoadTXD("tex/buildings/baguilok.txd")
engineImportTXD(txd, 2273)
dff = engineLoadDFF("tex/buildings/baguilok.dff", 2273)
engineReplaceModel(dff, 2273)
col = engineLoadCOL("tex/buildings/baguilok.col")
engineReplaceCOL(col,2273)
txd = engineLoadTXD("tex/buildings/GTA.la.txd")
engineImportTXD(txd, 2643)
txd = engineLoadTXD("tex/buildings/GTA.la.txd")
engineImportTXD(txd, 2641)
txd = engineLoadTXD("tex/buildings/Mesa.txd")
engineImportTXD(txd, 2027)
dff = engineLoadDFF("tex/buildings/Mesa.dff", 2027)
engineReplaceModel(dff, 2027)
col = engineLoadCOL("tex/buildings/Mesa.col")
engineReplaceCOL(col,2027)
txd = engineLoadTXD("tex/buildings/Mesa.txd")
engineImportTXD(txd, 1810)
dff = engineLoadDFF("tex/buildings/Silla.dff", 1810)
engineReplaceModel(dff, 1810)
col = engineLoadCOL("tex/buildings/Silla.col")
engineReplaceCOL(col,1810)
txd = engineLoadTXD("tex/buildings/Basura.txd")
engineImportTXD(txd, 1858)
dff = engineLoadDFF("tex/buildings/Basura.dff", 1858)
engineReplaceModel(dff, 1858)
col = engineLoadCOL("tex/buildings/Basura.col")
engineReplaceCOL(col,1858)
txd = engineLoadTXD("tex/buildings/Cajas.txd")
engineImportTXD(txd, 1860)
dff = engineLoadDFF("tex/buildings/Cajas.dff", 1860)
engineReplaceModel(dff, 1860)
col = engineLoadCOL("tex/buildings/Cajas.col")
engineReplaceCOL(col,1860)
txd = engineLoadTXD("tex/buildings/MuroL.txd")
engineImportTXD(txd, 1861)
dff = engineLoadDFF("tex/buildings/Muro.dff", 1861)
engineReplaceModel(dff, 1861)
col = engineLoadCOL("tex/buildings/Muro.col")
engineReplaceCOL(col,1861)
txd = engineLoadTXD("tex/buildings/MuroMe.txd")
engineImportTXD(txd, 1862)
dff = engineLoadDFF("tex/buildings/Muro.dff", 1862)
engineReplaceModel(dff, 1862)
col = engineLoadCOL("tex/buildings/Muro.col")
engineReplaceCOL(col,1862)
txd = engineLoadTXD("tex/buildings/MuroMa.txd")
engineImportTXD(txd, 1863)
dff = engineLoadDFF("tex/buildings/Muro.dff", 1863)
engineReplaceModel(dff, 1863)
col = engineLoadCOL("tex/buildings/Muro.col")
engineReplaceCOL(col,1863)
txd = engineLoadTXD("tex/buildings/Vegetacion.txd")
engineImportTXD(txd, 1855)
dff = engineLoadDFF("tex/buildings/Vegetacion.dff", 1855)
engineReplaceModel(dff, 1855)
col = engineLoadCOL("tex/buildings/Vegetacion.col")
engineReplaceCOL(col,1855)
dff = engineLoadDFF("tex/buildings/flare_light.dff", 1939)
engineReplaceModel(dff, 1939)
txd = engineLoadTXD("tex/buildings/wirefence.txd", 2411 )
engineImportTXD(txd, 2411)
dff = engineLoadDFF("tex/buildings/wirefence.dff", 2411 )
engineReplaceModel(dff, 2411)
col = engineLoadCOL("tex/buildings/wirefence.col")
engineReplaceCOL(col,2411)


txd = engineLoadTXD("tex/buildings/baraquement.txd")
engineImportTXD(txd, 18055)
dff = engineLoadDFF("tex/buildings/baraquement.dff", 18055)
engineReplaceModel(dff, 18055)
col = engineLoadCOL("tex/buildings/baraquement.col")
engineReplaceCOL(col,18055)

txd = engineLoadTXD("tex/buildings/controltower.txd")
engineImportTXD(txd, 14743)
dff = engineLoadDFF("tex/buildings/controltower.dff", 14743)
engineReplaceModel(dff, 14743)
col = engineLoadCOL("tex/buildings/controltower.col")
engineReplaceCOL(col,14743)

txd = engineLoadTXD("tex/buildings/fire.txd")
engineImportTXD(txd, 14619)
dff = engineLoadDFF("tex/buildings/fire.dff", 14619)
engineReplaceModel(dff, 14619)
col = engineLoadCOL("tex/buildings/fire.col")
engineReplaceCOL(col,14619)

txd = engineLoadTXD("tex/buildings/fires.txd")
engineImportTXD(txd, 14620)
dff = engineLoadDFF("tex/buildings/fires.dff", 14620)
engineReplaceModel(dff, 14620)
col = engineLoadCOL("tex/buildings/fires.col")
engineReplaceCOL(col,14620)

txd = engineLoadTXD("tex/buildings/medictent.txd")
engineImportTXD(txd, 14770)
dff = engineLoadDFF("tex/buildings/medictent.dff", 14770)
engineReplaceModel(dff, 14770)
col = engineLoadCOL("tex/buildings/medictent.col")
engineReplaceCOL(col,14770)

txd = engineLoadTXD("tex/buildings/tents2.txd")
engineImportTXD(txd, 14657)
dff = engineLoadDFF("tex/buildings/tents2.dff", 14657)
engineReplaceModel(dff, 14657)
col = engineLoadCOL("tex/buildings/tents2.col")
engineReplaceCOL(col,14657)

txd = engineLoadTXD("tex/buildings/teste.txd")
engineImportTXD(txd, 14490)
dff = engineLoadDFF("tex/buildings/teste.dff", 14490)
engineReplaceModel(dff, 14490)
col = engineLoadCOL("tex/buildings/teste.col")
engineReplaceCOL(col,14490)

txd = engineLoadTXD("tex/buildings/torre.txd")
engineImportTXD(txd, 14869)
dff = engineLoadDFF("tex/buildings/torre.dff", 14869)
engineReplaceModel(dff, 14869)
col = engineLoadCOL("tex/buildings/torre.col")
engineReplaceCOL(col,14869)
--------------
-- textures//
--------------
txd = engineLoadTXD ( "tex/player/army_male.txd" )
engineImportTXD ( txd, 19 )
dff = engineLoadDFF ( "tex/player/army_male.dff" )
engineReplaceModel ( dff, 19 )
txd = engineLoadTXD ( "tex/player/army_female.txd" )
engineImportTXD ( txd, 13 )
dff = engineLoadDFF ( "tex/player/army_female.dff" )
engineReplaceModel ( dff, 13 )
txd = engineLoadTXD ( "tex/player/civilian_male.txd" )
engineImportTXD ( txd, 1 )
dff = engineLoadDFF ( "tex/player/civilian_male.dff" )
engineReplaceModel ( dff, 1 )

txd = engineLoadTXD ( "tex/player/ghilliesuit.txd" )
engineImportTXD ( txd, 7 )
dff = engineLoadDFF ( "tex/player/ghilliesuit.dff" )
engineReplaceModel ( dff, 7 )

txd = engineLoadTXD ( "tex/player/bandit2_male.txd" )
engineImportTXD ( txd, 14 )
dff = engineLoadDFF ( "tex/player/bandit2_male.dff" )
engineReplaceModel ( dff, 14 )

txd = engineLoadTXD ( "tex/player/bandit3_male.txd" )
engineImportTXD ( txd, 15 )
dff = engineLoadDFF ( "tex/player/bandit3_male.dff" )
engineReplaceModel ( dff, 15 )

txd = engineLoadTXD ( "tex/player/hero_male.txd" )
engineImportTXD ( txd, 17 )
dff = engineLoadDFF ( "tex/player/hero_male.dff" )
engineReplaceModel ( dff, 17 )

txd = engineLoadTXD ( "tex/player/standard_male.txd" )
engineImportTXD ( txd, 18 )
dff = engineLoadDFF ( "tex/player/standard_male.dff" )
engineReplaceModel ( dff, 18 )

txd = engineLoadTXD ( "tex/player/bandit1_female.txd" )
engineImportTXD ( txd, 9 )
dff = engineLoadDFF ( "tex/player/bandit1_female.dff" )
engineReplaceModel ( dff, 9 )

txd = engineLoadTXD ( "tex/player/bandit2_female.txd" )
engineImportTXD ( txd, 10 )
dff = engineLoadDFF ( "tex/player/bandit2_female.dff" )
engineReplaceModel ( dff, 10 )

txd = engineLoadTXD ( "tex/player/civilian_female.txd" )
engineImportTXD ( txd, 11 )
dff = engineLoadDFF ( "tex/player/civilian_female.dff" )
engineReplaceModel ( dff, 11 )

txd = engineLoadTXD ( "tex/player/police_man.txd" )
engineImportTXD ( txd, 40 )
dff = engineLoadDFF ( "tex/player/police_man.dff" )
engineReplaceModel ( dff, 40 )

--------------
-- AUTOS//
--------------


--------------
-- animals//
--------------
txd = engineLoadTXD ( "tex/animals/Oso.txd" )
engineImportTXD ( txd, 312 )
dff = engineLoadDFF ( "tex/animals/Oso.dff" )
engineReplaceModel ( dff, 312 )
txd = engineLoadTXD ( "tex/animals/Baca1.txd" )
engineImportTXD ( txd, 311 )
dff = engineLoadDFF ( "tex/animals/Baca1.dff" )
engineReplaceModel ( dff, 311 )
txd = engineLoadTXD ( "tex/animals/Baca2.txd" )
engineImportTXD ( txd, 310 )
dff = engineLoadDFF ( "tex/animals/Baca2.dff" )
engineReplaceModel ( dff, 310 )
txd = engineLoadTXD ( "tex/animals/Lobo.txd" )
engineImportTXD ( txd, 309 )
dff = engineLoadDFF ( "tex/animals/Lobo.dff" )
engineReplaceModel ( dff, 309 )
txd = engineLoadTXD ( "tex/animals/Cabra.txd" )
engineImportTXD ( txd, 308 )
dff = engineLoadDFF ( "tex/animals/Cabra.dff" )
engineReplaceModel ( dff, 308 )
txd = engineLoadTXD ( "tex/animals/Zorro.txd" )
engineImportTXD ( txd, 307 )
dff = engineLoadDFF ( "tex/animals/Zorro.dff" )
engineReplaceModel ( dff, 307 )

--------------
-- backpacks//
--------------
txd = engineLoadTXD ( "tex/backpacks/Coyote.txd" )
engineImportTXD ( txd, 1252 )
dff = engineLoadDFF ( "tex/backpacks/Coyote.dff" )
engineReplaceModel ( dff, 1252 )
txd = engineLoadTXD ( "tex/backpacks/Militar.txd" )
engineImportTXD ( txd, 2408 )
dff = engineLoadDFF ( "tex/backpacks/Militar.dff" )
engineReplaceModel ( dff, 2408 )
txd = engineLoadTXD ( "tex/backpacks/Ossier.txd" )
engineImportTXD ( txd, 1575 )
dff = engineLoadDFF ( "tex/backpacks/Ossier.dff" )
engineReplaceModel ( dff, 1575 )
txd = engineLoadTXD ( "tex/backpacks/Gamespot.txd" )
engineImportTXD ( txd, 2399 )
dff = engineLoadDFF ( "tex/backpacks/Gamespot.dff" )
engineReplaceModel ( dff, 2399 )
txd = engineLoadTXD ( "tex/backpacks/Alice.txd" )
engineImportTXD ( txd, 1248 )
dff = engineLoadDFF ( "tex/backpacks/Alice.dff" )
engineReplaceModel ( dff, 1248 )
txd = engineLoadTXD ( "tex/backpacks/Asalto.txd" )
engineImportTXD ( txd, 2401 )
dff = engineLoadDFF ( "tex/backpacks/Asalto.dff" )
engineReplaceModel ( dff, 2401 )
txd = engineLoadTXD ( "tex/backpacks/Krysset.txd" )
engineImportTXD ( txd, 2398 )
dff = engineLoadDFF ( "tex/backpacks/Krysset.dff" )
engineReplaceModel ( dff, 2398 )
txd = engineLoadTXD ( "tex/backpacks/Livie.txd" )
engineImportTXD ( txd, 2397 )
dff = engineLoadDFF ( "tex/backpacks/Livie.dff" )
engineReplaceModel ( dff, 2397 )
txd = engineLoadTXD ( "tex/backpacks/Rucksack.txd" )
engineImportTXD ( txd, 2396 )
dff = engineLoadDFF ( "tex/backpacks/Rucksack.dff" )
engineReplaceModel ( dff, 2396 )

txd = engineLoadTXD ( "tex/backpacks/guillie.txd" )
engineImportTXD ( txd, 1577 )
dff = engineLoadDFF ( "tex/backpacks/guillie.dff" )
engineReplaceModel ( dff, 1577 )
txd = engineLoadTXD ( "tex/backpacks/improvised.txd" )
engineImportTXD ( txd, 1242 )
dff = engineLoadDFF ( "tex/backpacks/improvised.dff" )
engineReplaceModel ( dff, 1242 )
txd = engineLoadTXD ( "tex/backpacks/mountain.txd" )
engineImportTXD ( txd, 1310 )
dff = engineLoadDFF ( "tex/backpacks/mountain.dff" )
engineReplaceModel ( dff, 1310 )
txd = engineLoadTXD ( "tex/backpacks/mountain_light.txd" )
engineImportTXD ( txd, 1275 )
dff = engineLoadDFF ( "tex/backpacks/mountain_light.dff" )
engineReplaceModel ( dff, 1275 )
txd = engineLoadTXD ( "tex/backpacks/cabo.txd" )
engineImportTXD ( txd, 1274 )
dff = engineLoadDFF ( "tex/backpacks/cabo.dff" )
engineReplaceModel ( dff, 1274 )
txd = engineLoadTXD ( "tex/backpacks/czech.txd" )
engineImportTXD ( txd, 1273 )
dff = engineLoadDFF ( "tex/backpacks/czech.dff" )
engineReplaceModel ( dff, 1273 )
txd = engineLoadTXD ( "tex/backpacks/survivor.txd" )
engineImportTXD ( txd, 1272 )
dff = engineLoadDFF ( "tex/backpacks/survivor.dff" )
engineReplaceModel ( dff, 1272 )
txd = engineLoadTXD ( "tex/backpacks/assault_light.txd" )
engineImportTXD ( txd, 1254 )
dff = engineLoadDFF ( "tex/backpacks/assault_light.dff" )
engineReplaceModel ( dff, 1254 )
txd = engineLoadTXD ( "tex/backpacks/schoolar.txd" )
engineImportTXD ( txd, 1314 )
dff = engineLoadDFF ( "tex/backpacks/schoolar.dff" )
engineReplaceModel ( dff, 1314 )
txd = engineLoadTXD ( "tex/backpacks/coyote_camo.txd" )
engineImportTXD ( txd, 1313 )
dff = engineLoadDFF ( "tex/backpacks/coyote_camo.dff" )
engineReplaceModel ( dff, 1313 )
txd = engineLoadTXD ( "tex/backpacks/camping.txd" )
engineImportTXD ( txd, 1318 )
dff = engineLoadDFF ( "tex/backpacks/camping.dff" )
engineReplaceModel ( dff, 1318 )
txd = engineLoadTXD ( "tex/backpacks/camping.txd" )
engineImportTXD ( txd, 1318 )
dff = engineLoadDFF ( "tex/backpacks/camping.dff" )
engineReplaceModel ( dff, 1318 )
txd = engineLoadTXD ( "tex/backpacks/sfg_military.txd" )
engineImportTXD ( txd, 1672 )
dff = engineLoadDFF ( "tex/backpacks/sfg_military.dff" )
engineReplaceModel ( dff, 1672 )
--------------
-- weapons//
--------------
txd = engineLoadTXD ( "tex/weapons/AKSGold.txd" )
engineImportTXD ( txd, 2833 )
dff = engineLoadDFF ( "tex/weapons/AKSGold.dff" )
engineReplaceModel ( dff, 2833 )
txd = engineLoadTXD ( "tex/weapons/HecateII.txd" )
engineImportTXD ( txd, 2827 )
dff = engineLoadDFF ( "tex/weapons/HecateII.dff" )
engineReplaceModel ( dff, 2827 )
txd = engineLoadTXD ( "tex/weapons/Barret_50.txd" )
engineImportTXD ( txd, 2826 )
dff = engineLoadDFF ( "tex/weapons/Barret_50.dff" )
engineReplaceModel ( dff, 2826 )
txd = engineLoadTXD ( "tex/weapons/binoculars.txd" )
engineImportTXD ( txd, 367 )
dff = engineLoadDFF ( "tex/weapons/binoculars.dff" )
engineReplaceModel ( dff, 367 )
txd = engineLoadTXD ( "tex/weapons/Dragunov.txd" )
engineImportTXD ( txd, 2812 )
dff = engineLoadDFF ( "tex/weapons/Dragunov.dff" )
engineReplaceModel ( dff, 2812 )
txd = engineLoadTXD ( "tex/weapons/G28.txd" )
engineImportTXD ( txd, 2834 )
dff = engineLoadDFF ( "tex/weapons/G28.dff" )
engineReplaceModel ( dff, 2834 )
txd = engineLoadTXD ( "tex/weapons/Benelli_92.txd" )
engineImportTXD ( txd, 2835 )
dff = engineLoadDFF ( "tex/weapons/Benelli_92.dff" )
engineReplaceModel ( dff, 2835 )
txd = engineLoadTXD ( "tex/weapons/M870.txd" )
engineImportTXD ( txd, 2855 )
dff = engineLoadDFF ( "tex/weapons/M870.dff" )
engineReplaceModel ( dff, 2855 )
txd = engineLoadTXD ( "tex/weapons/Winchester_1894.txd" )
engineImportTXD ( txd, 2836 )
dff = engineLoadDFF ( "tex/weapons/Winchester_1894.dff" )
engineReplaceModel ( dff, 2836 )
txd = engineLoadTXD ( "tex/weapons/M1911.txd" )
engineImportTXD ( txd, 2843 )
dff = engineLoadDFF ( "tex/weapons/M1911.dff" )
engineReplaceModel ( dff, 2843 )
txd = engineLoadTXD ( "tex/weapons/IMI_Galil.txd" )
engineImportTXD ( txd, 2845 )
dff = engineLoadDFF ( "tex/weapons/IMI_Galil.dff" )
engineReplaceModel ( dff, 2845 )
txd = engineLoadTXD ( "tex/weapons/Beretta-M92F.txd" )
engineImportTXD ( txd, 2844 )
dff = engineLoadDFF ( "tex/weapons/Beretta-M92F.dff" )
engineReplaceModel ( dff, 2844 )
txd = engineLoadTXD ( "tex/weapons/Desert_Eagle.txd" )
engineImportTXD ( txd, 2846 )
dff = engineLoadDFF ( "tex/weapons/Desert_Eagle.dff" )
engineReplaceModel ( dff, 2846 )
txd = engineLoadTXD ( "tex/weapons/Beretta_M9.txd" )
engineImportTXD ( txd, 2869 )
dff = engineLoadDFF ( "tex/weapons/Beretta_M9.dff" )
engineReplaceModel ( dff, 2869 )
txd = engineLoadTXD ( "tex/weapons/FN_FAL.txd" )
engineImportTXD ( txd, 2868 )
dff = engineLoadDFF ( "tex/weapons/FN_FAL.dff" )
engineReplaceModel ( dff, 2868 )
txd = engineLoadTXD ( "tex/weapons/FNC.txd" )
engineImportTXD ( txd, 2865 )
dff = engineLoadDFF ( "tex/weapons/FNC.dff" )
engineReplaceModel ( dff, 2865 )
txd = engineLoadTXD ( "tex/weapons/Crossbow.txd" )
engineImportTXD ( txd, 2841 )
dff = engineLoadDFF ( "tex/weapons/Crossbow.dff" )
engineReplaceModel ( dff, 2841 )
txd = engineLoadTXD ( "tex/weapons/AK-74_PSO.txd" )
engineImportTXD ( txd, 2842 )
dff = engineLoadDFF ( "tex/weapons/AK-74_PSO.dff" )
engineReplaceModel ( dff, 2842 )
txd = engineLoadTXD ( "tex/weapons/AKS-74UN_Kobra.txd" )
engineImportTXD ( txd, 2828 )
dff = engineLoadDFF ( "tex/weapons/AKS-74UN_Kobra.dff" )
engineReplaceModel ( dff, 2828 )
txd = engineLoadTXD ( "tex/weapons/ACR.txd" )
engineImportTXD ( txd, 2829 )
dff = engineLoadDFF ( "tex/weapons/ACR.dff" )
engineReplaceModel ( dff, 2829 )
txd = engineLoadTXD ( "tex/weapons/AK74.txd" )
engineImportTXD ( txd, 2830 )
dff = engineLoadDFF ( "tex/weapons/AK74.dff" )
engineReplaceModel ( dff, 2830 )
txd = engineLoadTXD ( "tex/weapons/Steyr_AUG.txd" )
engineImportTXD ( txd, 2831 )
dff = engineLoadDFF ( "tex/weapons/Steyr_AUG.dff" )
engineReplaceModel ( dff, 2831 )
txd = engineLoadTXD ( "tex/weapons/Knife.txd" )
engineImportTXD ( txd, 2832 )
dff = engineLoadDFF ( "tex/weapons/Knife.dff" )
engineReplaceModel ( dff, 2832 )
txd = engineLoadTXD ( "tex/weapons/Crowbar.txd" )
engineImportTXD ( txd, 2848 )
dff = engineLoadDFF ( "tex/weapons/Crowbar.dff" )
engineReplaceModel ( dff, 2848 )
txd = engineLoadTXD ( "tex/weapons/AXE.txd" )
engineImportTXD ( txd, 2849 )
dff = engineLoadDFF ( "tex/weapons/AXE.dff" )
engineReplaceModel ( dff, 2849 )
txd = engineLoadTXD ( "tex/weapons/USP45.txd" )
engineImportTXD ( txd, 2850 )
dff = engineLoadDFF ( "tex/weapons/USP45.dff" )
engineReplaceModel ( dff, 2850 )
txd = engineLoadTXD ( "tex/weapons/USP45SD.txd" )
engineImportTXD ( txd, 2851 )
dff = engineLoadDFF ( "tex/weapons/USP45SD.dff" )
engineReplaceModel ( dff, 2851 )
txd = engineLoadTXD ( "tex/weapons/G36C.txd" )
engineImportTXD ( txd, 2852 )
dff = engineLoadDFF ( "tex/weapons/G36C.dff" )
engineReplaceModel ( dff, 2852 )
txd = engineLoadTXD ( "tex/weapons/Revolver_Colt.txd" )
engineImportTXD ( txd, 2853 )
dff = engineLoadDFF ( "tex/weapons/Revolver_Colt.dff" )
engineReplaceModel ( dff, 2853 )
txd = engineLoadTXD ( "tex/weapons/M16.txd" )
engineImportTXD ( txd, 2854 )
dff = engineLoadDFF ( "tex/weapons/M16.dff" )
engineReplaceModel ( dff, 2854 )
txd = engineLoadTXD ( "tex/weapons/Bizon.txd" )
engineImportTXD ( txd, 2862 )
dff = engineLoadDFF ( "tex/weapons/Bizon.dff" )
engineReplaceModel ( dff, 2862 )
txd = engineLoadTXD ( "tex/weapons/CZ550.txd" )
engineImportTXD ( txd, 1659 )
dff = engineLoadDFF ( "tex/weapons/CZ550.dff" )
engineReplaceModel ( dff, 1659 )
txd = engineLoadTXD ( "tex/weapons/PDW.txd" )
engineImportTXD ( txd, 2870 )
dff = engineLoadDFF ( "tex/weapons/PDW.dff" )
engineReplaceModel ( dff, 2870 )
txd = engineLoadTXD ( "tex/weapons/MP5A5.txd" )
engineImportTXD ( txd, 2864 )
dff = engineLoadDFF ( "tex/weapons/MP5A5.dff" )
engineReplaceModel ( dff, 2864 )
txd = engineLoadTXD("tex/weapons/M4A3_CCO.txd")
engineImportTXD(txd, 2816)
dff = engineLoadDFF("tex/weapons/M4A3_CCO.dff", 2816)
engineReplaceModel(dff, 2816)
txd = engineLoadTXD("tex/weapons/M107.txd")
engineImportTXD(txd, 2817)
dff = engineLoadDFF("tex/weapons/M107.dff", 2817)
engineReplaceModel(dff, 2817)
txd = engineLoadTXD("tex/weapons/AS50.txd")
engineImportTXD(txd, 2818)
dff = engineLoadDFF("tex/weapons/AS50.dff", 2818)
engineReplaceModel(dff, 2818)
txd = engineLoadTXD("tex/weapons/Mk14_EBR.txd")
engineImportTXD(txd, 2819)
dff = engineLoadDFF("tex/weapons/Mk14_EBR.dff", 2819)
engineReplaceModel(dff, 2819)
txd = engineLoadTXD("tex/weapons/Mk48.txd")
engineImportTXD(txd, 2820)
dff = engineLoadDFF("tex/weapons/Mk48.dff", 2820)
engineReplaceModel(dff, 2820)
txd = engineLoadTXD("tex/weapons/PKM.txd")
engineImportTXD(txd, 2822)
dff = engineLoadDFF("tex/weapons/PKM.dff", 2822)
engineReplaceModel(dff, 2822)
txd = engineLoadTXD("tex/weapons/M203.txd")
engineImportTXD(txd, 2824)
dff = engineLoadDFF("tex/weapons/M203.dff", 2824)
engineReplaceModel(dff, 2824)
txd = engineLoadTXD("tex/weapons/arrow.txd")
engineImportTXD(txd, 1247)
dff = engineLoadDFF("tex/weapons/arrow.dff", 1247)
engineReplaceModel(dff, 1247)

txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 339 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 339 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 335 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 335 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 336 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 336 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 347 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 347 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 348 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 348 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 349 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 349 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 353 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 353 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 356 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 356 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 357 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 357 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 358 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 358 )
txd = engineLoadTXD ( "tex/weapons/wbse.txd" )
engineImportTXD ( txd, 355 )
dff = engineLoadDFF ( "tex/weapons/wbse.dff" )
engineReplaceModel ( dff, 355 )

--------------
-- ITEMS//
--------------
txd = engineLoadTXD("tex/items/fireplace.txd")
engineImportTXD(txd, 1906)
dff = engineLoadDFF("tex/items/fireplace.dff")
engineReplaceModel(dff, 1906)
txd = engineLoadTXD("tex/items/compass.txd")
engineImportTXD(txd, 1937)
dff = engineLoadDFF("tex/items/compass.dff", 1937)
engineReplaceModel(dff, 1937)
txd = engineLoadTXD("tex/items/beans_can.txd")
engineImportTXD(txd, 2601)
dff = engineLoadDFF("tex/items/beans_can.dff", 2601)
engineReplaceModel(dff, 2601)
txd = engineLoadTXD("tex/items/pasta_can.txd")
engineImportTXD(txd, 2770)
dff = engineLoadDFF("tex/items/pasta_can.dff", 2770)
engineReplaceModel(dff, 2770)
txd = engineLoadTXD("tex/items/sardines_can.txd")
engineImportTXD(txd, 2798)
dff = engineLoadDFF("tex/items/sardines_can.dff", 2798)
engineReplaceModel(dff, 2798)
txd = engineLoadTXD("tex/items/frank_can.txd")
engineImportTXD(txd, 953)
dff = engineLoadDFF("tex/items/frank_can.dff", 953)
engineReplaceModel(dff, 953)
txd = engineLoadTXD("tex/items/mre.txd")
engineImportTXD(txd, 2058)
dff = engineLoadDFF("tex/items/mre.dff", 2058)
engineReplaceModel(dff, 2058)
txd = engineLoadTXD("tex/items/doritos.txd")
engineImportTXD(txd, 2407)
dff = engineLoadDFF("tex/items/doritos.dff", 2407)
engineReplaceModel(dff, 2407)
txd = engineLoadTXD("tex/items/can_corn.txd")
engineImportTXD(txd, 2238)
dff = engineLoadDFF("tex/items/can_corn.dff", 2238)
engineReplaceModel(dff, 2238)
txd = engineLoadTXD("tex/items/can_peas.txd")
engineImportTXD(txd, 2108)
dff = engineLoadDFF("tex/items/can_peas.dff", 2108)
engineReplaceModel(dff, 2108)
txd = engineLoadTXD("tex/items/can_stew.txd")
engineImportTXD(txd, 2107)
dff = engineLoadDFF("tex/items/can_stew.dff", 2107)
engineReplaceModel(dff, 2107)
txd = engineLoadTXD("tex/items/can_pork.txd")
engineImportTXD(txd, 2106)
dff = engineLoadDFF("tex/items/can_pork.dff", 2106)
engineReplaceModel(dff, 2106)
txd = engineLoadTXD("tex/items/can_fruits.txd")
engineImportTXD(txd, 2105)
dff = engineLoadDFF("tex/items/can_fruits.dff", 2105)
engineReplaceModel(dff, 2105)
txd = engineLoadTXD("tex/items/can_chowder.txd")
engineImportTXD(txd, 2077)
dff = engineLoadDFF("tex/items/can_chowder.dff", 2077)
engineReplaceModel(dff, 2077)
txd = engineLoadTXD("tex/items/can_ravioli.txd")
engineImportTXD(txd, 2066)
dff = engineLoadDFF("tex/items/can_ravioli.dff", 2066)
engineReplaceModel(dff, 2066)
txd = engineLoadTXD("tex/items/can_milk.txd")
engineImportTXD(txd, 2076)
dff = engineLoadDFF("tex/items/can_milk.dff", 2076)
engineReplaceModel(dff, 2076)
txd = engineLoadTXD("tex/items/cookedmeat.txd")
engineImportTXD(txd, 2404)
dff = engineLoadDFF("tex/items/cookedmeat.dff", 2404)
engineReplaceModel(dff, 2404)
txd = engineLoadTXD("tex/items/rawmeat.txd")
engineImportTXD(txd, 2804)
dff = engineLoadDFF("tex/items/rawmeat.dff", 2804)
engineReplaceModel(dff, 2804)
txd = engineLoadTXD("tex/items/cola_can.txd")
engineImportTXD(txd, 2647)
dff = engineLoadDFF("tex/items/cola_can.dff", 2647)
engineReplaceModel(dff, 2647)
txd = engineLoadTXD("tex/items/dew_can.txd")
engineImportTXD(txd, 2405)
dff = engineLoadDFF("tex/items/dew_can.dff", 2405)
engineReplaceModel(dff, 2405)
txd = engineLoadTXD("tex/items/pepsi_can.txd")
engineImportTXD(txd, 2406)
dff = engineLoadDFF("tex/items/pepsi_can.dff", 2406)
engineReplaceModel(dff, 2406)
txd = engineLoadTXD("tex/items/waterbottle.txd")
engineImportTXD(txd, 2683)
dff = engineLoadDFF("tex/items/waterbottle.dff", 2683)
engineReplaceModel(dff, 2683)
txd = engineLoadTXD("tex/items/antibiotics.txd")
engineImportTXD(txd, 330)
dff = engineLoadDFF("tex/items/antibiotics.dff", 330)
engineReplaceModel(dff, 330)
txd = engineLoadTXD("tex/items/bandage.txd")
engineImportTXD(txd, 1578)
dff = engineLoadDFF("tex/items/bandage.dff", 1578)
engineReplaceModel(dff, 1578)
txd = engineLoadTXD("tex/items/bloodbag.txd")
engineImportTXD(txd, 1580)
dff = engineLoadDFF("tex/items/bloodbag.dff", 1580)
engineReplaceModel(dff, 1580)
txd = engineLoadTXD("tex/items/engine.txd")
engineImportTXD(txd, 2782)
dff = engineLoadDFF("tex/items/engine.dff", 2782)
engineReplaceModel(dff, 2782)
txd = engineLoadTXD("tex/items/batery.txd")
engineImportTXD(txd, 1851)
dff = engineLoadDFF("tex/items/batery.dff", 1851)
engineReplaceModel(dff, 1851)
txd = engineLoadTXD("tex/items/tire.txd")
engineImportTXD(txd, 1852)
dff = engineLoadDFF("tex/items/tire.dff", 1852)
engineReplaceModel(dff, 1852)
txd = engineLoadTXD("tex/items/rotary.txd")
engineImportTXD(txd, 2056)
dff = engineLoadDFF("tex/items/rotary.dff", 2056)
engineReplaceModel(dff, 2056)
txd = engineLoadTXD("tex/items/fueltank.txd")
engineImportTXD(txd, 1947)
dff = engineLoadDFF("tex/items/fueltank.dff", 1947)
engineReplaceModel(dff, 1947)
txd = engineLoadTXD("tex/items/morphine.txd")
engineImportTXD(txd, 958)
dff = engineLoadDFF("tex/items/morphine.dff", 958)
engineReplaceModel(dff, 958)
txd = engineLoadTXD("tex/items/painkillers.txd")
engineImportTXD(txd, 2709)
dff = engineLoadDFF("tex/items/painkillers.dff", 2709)
engineReplaceModel(dff, 2709)
txd = engineLoadTXD("tex/items/first_aid_kit.txd")
engineImportTXD(txd, 2891)
dff = engineLoadDFF("tex/items/first_aid_kit.dff", 2891)
engineReplaceModel(dff, 2891)
txd = engineLoadTXD("tex/items/heatpack.txd")
engineImportTXD(txd, 1579)
dff = engineLoadDFF("tex/items/heatpack.dff", 1579)
engineReplaceModel(dff, 1579)
txd = engineLoadTXD("tex/items/gps.txd")
engineImportTXD(txd, 2976)
dff = engineLoadDFF("tex/items/gps.dff", 2976)
engineReplaceModel(dff, 2976)
txd = engineLoadTXD("tex/items/map.txd")
engineImportTXD(txd, 1277)
dff = engineLoadDFF("tex/items/map.dff", 1277)
engineReplaceModel(dff, 1277)
txd = engineLoadTXD("tex/items/toolbox.txd")
engineImportTXD(txd, 2969)
dff = engineLoadDFF("tex/items/toolbox.dff", 2969)
engineReplaceModel(dff, 2969)
txd = engineLoadTXD("tex/items/matches.txd")
engineImportTXD(txd, 328)
dff = engineLoadDFF("tex/items/matches.dff", 328)
engineReplaceModel(dff, 328)
txd = engineLoadTXD("tex/items/watch.txd")
engineImportTXD(txd, 2710)
dff = engineLoadDFF("tex/items/watch.dff", 2710)
engineReplaceModel(dff, 2710)
txd = engineLoadTXD("tex/items/woodpile.txd")
engineImportTXD(txd, 1463)
dff = engineLoadDFF("tex/items/woodpile.dff", 1463)
engineReplaceModel(dff, 1463)
txd = engineLoadTXD("tex/items/tincan_empty.txd")
engineImportTXD(txd, 2694)
dff = engineLoadDFF("tex/items/tincan_empty.dff", 2694)
engineReplaceModel(dff, 2694)
txd = engineLoadTXD("tex/items/campingtent.txd")
engineImportTXD(txd, 1279)
dff = engineLoadDFF("tex/items/campingtent.dff", 1279)
engineReplaceModel(dff, 1279)
txd = engineLoadTXD("tex/items/roadflare.txd")
engineImportTXD(txd, 324)
dff = engineLoadDFF("tex/items/roadflare.dff", 324)
engineReplaceModel(dff, 324)
txd = engineLoadTXD("tex/items/jerrycan.txd")
engineImportTXD(txd, 1650)
dff = engineLoadDFF("tex/items/jerrycan.dff", 1650)
engineReplaceModel(dff, 1650)
txd = engineLoadTXD("tex/items/metal.txd")
engineImportTXD(txd, 3104)
dff = engineLoadDFF("tex/items/metal.dff", 3104)
engineReplaceModel(dff, 3104)
txd = engineLoadTXD("tex/items/9x18cartridge.txd")
engineImportTXD(txd, 2057)
dff = engineLoadDFF("tex/items/9x18cartridge.dff", 2057)
engineReplaceModel(dff, 2057)
txd = engineLoadTXD("tex/items/sniper_ammo.txd")
engineImportTXD(txd, 2711)
dff = engineLoadDFF("tex/items/sniper_ammo.dff", 2711)
engineReplaceModel(dff, 2711)
txd = engineLoadTXD("tex/items/9x19cartridge.txd")
engineImportTXD(txd, 2041)
dff = engineLoadDFF("tex/items/9x19cartridge.dff", 2041)
engineReplaceModel(dff, 2041)
txd = engineLoadTXD("tex/items/12gauge.txd")
engineImportTXD(txd, 2362)
dff = engineLoadDFF("tex/items/12gauge.dff", 2362)
engineReplaceModel(dff, 2362)
txd = engineLoadTXD("tex/items/308winchester.txd")
engineImportTXD(txd, 2036)
dff = engineLoadDFF("tex/items/308winchester.dff", 2036)
engineReplaceModel(dff, 2036)
txd = engineLoadTXD("tex/items/545x39cartridge.txd")
engineImportTXD(txd, 1271)
dff = engineLoadDFF("tex/items/545x39cartridge.dff", 1271)
engineReplaceModel(dff, 1271)
txd = engineLoadTXD("tex/items/556x45cartridge.txd")
engineImportTXD(txd, 2035)
dff = engineLoadDFF("tex/items/556x45cartridge.dff", 2035)
engineReplaceModel(dff, 2035)
txd = engineLoadTXD("tex/items/762x51cartridge.txd")
engineImportTXD(txd, 2034)
dff = engineLoadDFF("tex/items/762x51cartridge.dff", 2034)
engineReplaceModel(dff, 2034)
txd = engineLoadTXD("tex/items/762x54cartridge.txd")
engineImportTXD(txd, 2358)
dff = engineLoadDFF("tex/items/762x54cartridge.dff", 2358)
engineReplaceModel(dff, 2358)
txd = engineLoadTXD("tex/items/1143x23cartridge.txd")
engineImportTXD(txd, 3013)
dff = engineLoadDFF("tex/items/1143x23cartridge.dff", 3013)
engineReplaceModel(dff, 3013)
txd = engineLoadTXD("tex/items/1866slug.txd")
engineImportTXD(txd, 2033)
dff = engineLoadDFF("tex/items/1866slug.dff", 2033)
engineReplaceModel(dff, 2033)
txd = engineLoadTXD("tex/items/basic_helmet.txd")
engineImportTXD(txd, 1832)
dff = engineLoadDFF("tex/items/basic_helmet.dff", 1832)
engineReplaceModel(dff, 1832)
txd = engineLoadTXD("tex/items/moto_helmet.txd")
engineImportTXD(txd, 1833)
dff = engineLoadDFF("tex/items/moto_helmet.dff", 1833)
engineReplaceModel(dff, 1833)
txd = engineLoadTXD("tex/items/war_helmet.txd")
engineImportTXD(txd, 1834)
dff = engineLoadDFF("tex/items/war_helmet.dff", 1834)
engineReplaceModel(dff, 1834)
txd = engineLoadTXD("tex/items/war_kevlar.txd")
engineImportTXD(txd, 1836)
dff = engineLoadDFF("tex/items/war_kevlar.dff", 1836)
engineReplaceModel(dff, 1836)
txd = engineLoadTXD("tex/items/civillian_kevlar.txd")
engineImportTXD(txd, 1837)
dff = engineLoadDFF("tex/items/civillian_kevlar.dff", 1837)
engineReplaceModel(dff, 1837)
txd = engineLoadTXD("tex/items/basic_kevlar.txd")
engineImportTXD(txd, 1838)
dff = engineLoadDFF("tex/items/basic_kevlar.dff", 1838)
engineReplaceModel(dff, 1838)
txd = engineLoadTXD ( "tex/items/old_helmet.txd" )
engineImportTXD ( txd, 1830 )
dff = engineLoadDFF ( "tex/items/old_helmet.dff" )
engineReplaceModel ( dff, 1830 )
txd = engineLoadTXD ( "tex/items/police_kevlar.txd" )
engineImportTXD ( txd, 1831 )
dff = engineLoadDFF ( "tex/items/police_kevlar.dff" )
engineReplaceModel ( dff, 1831 )
txd = engineLoadTXD("tex/items/mine.txd")
engineImportTXD(txd, 1864)
dff = engineLoadDFF("tex/items/mine.dff", 1864)
engineReplaceModel(dff, 1864)
txd = engineLoadTXD("tex/items/bear_tramp_unpack.txd")
engineImportTXD(txd, 1865)
dff = engineLoadDFF("tex/items/bear_tramp_unpack.dff", 1865)
engineReplaceModel(dff, 1865)
txd = engineLoadTXD("tex/items/bear_tramp.txd")
engineImportTXD(txd, 1866)
dff = engineLoadDFF("tex/items/bear_tramp.dff", 1866)
engineReplaceModel(dff, 1866)
col = engineLoadCOL("tex/items/bear_tramp.col")
engineReplaceCOL(col, 1866)
txd = engineLoadTXD("tex/items/transfusionkit.txd")
engineImportTXD(txd, 1867)
dff = engineLoadDFF("tex/items/transfusionkit.dff", 1867)
engineReplaceModel(dff, 1867)
txd = engineLoadTXD("tex/items/tincan_empty.txd")
engineImportTXD(txd, 1213)
dff = engineLoadDFF("tex/items/tincan_empty.dff", 1213)
engineReplaceModel(dff, 1213)
txd = engineLoadTXD("tex/items/sodacan_empty.txd")
engineImportTXD(txd, 1576)
dff = engineLoadDFF("tex/items/sodacan_empty.dff", 1576)
engineReplaceModel(dff, 1576)
txd = engineLoadTXD("tex/items/wirefencekit.txd", 1945)
engineImportTXD(txd, 1945)
dff = engineLoadDFF("tex/items/wirefencekit.dff", 1945)
engineReplaceModel(dff, 1945)
txd = engineLoadTXD("tex/items/steroids.txd", 1938)
engineImportTXD(txd, 1938)
dff = engineLoadDFF("tex/items/steroids.dff", 1938)
engineReplaceModel(dff, 1938)
txd = engineLoadTXD("tex/items/clothing.txd", 1870)
engineImportTXD(txd, 1870)
dff = engineLoadDFF("tex/items/clothing.dff", 1870)
engineReplaceModel(dff, 1870)



----------------------
-- VEHICLES//
----------------------
--[[
txd = engineLoadTXD("tex/vehicles/sanchez.txd", 468 )
engineImportTXD(txd, 468)
dff = engineLoadDFF("tex/vehicles/sanchez.dff", 468 )
engineReplaceModel(dff, 468)
txd = engineLoadTXD("tex/vehicles/barracks.txd", 433 )
engineImportTXD(txd, 433)
dff = engineLoadDFF("tex/vehicles/barracks.dff", 433 )
engineReplaceModel(dff, 433)

txd = engineLoadTXD("tex/vehicles/patriot.txd", 470 )
engineImportTXD(txd, 470)
dff = engineLoadDFF("tex/vehicles/patriot.dff", 470 )
engineReplaceModel(dff, 470)
txd = engineLoadTXD("tex/vehicles/infernus.txd", 411 )
engineImportTXD(txd, 411)
dff = engineLoadDFF("tex/vehicles/infernus.dff", 411 )
engineReplaceModel(dff, 411)
txd = engineLoadTXD("tex/vehicles/bobcat.txd", 422 )
engineImportTXD(txd, 422)
dff = engineLoadDFF("tex/vehicles/bobcat.dff", 422 )
engineReplaceModel(dff, 422)
txd = engineLoadTXD("tex/vehicles/bandito.txd", 568 )
engineImportTXD(txd, 568)
dff = engineLoadDFF("tex/vehicles/bandito.dff", 568 )
engineReplaceModel(dff, 568)

txd = engineLoadTXD("tex/vehicles/bus.txd", 431 )
engineImportTXD(txd, 431)
dff = engineLoadDFF("tex/vehicles/bus.dff", 431 )
engineReplaceModel(dff, 431)
txd = engineLoadTXD("tex/vehicles/mtbike.txd", 510 )
engineImportTXD(txd, 510)
dff = engineLoadDFF("tex/vehicles/mtbike.dff", 510 )
engineReplaceModel(dff, 510)
txd = engineLoadTXD("tex/vehicles/blistac.txd", 496 )
engineImportTXD(txd, 496)
dff = engineLoadDFF("tex/vehicles/blistac.dff", 496 )
engineReplaceModel(dff, 496)
txd = engineLoadTXD("tex/vehicles/raindanc.txd", 563 )
engineImportTXD(txd, 563)
dff = engineLoadDFF("tex/vehicles/raindanc.dff", 563 )
engineReplaceModel(dff, 563)

txd = engineLoadTXD("tex/vehicles/bfinject.txd", 424 )
engineImportTXD(txd, 424)
dff = engineLoadDFF("tex/vehicles/bfinject.dff", 424 )
engineReplaceModel(dff, 424)

txd = engineLoadTXD("tex/vehicles/buffalo.txd", 402 )
engineImportTXD(txd, 402)
dff = engineLoadDFF("tex/vehicles/buffalo.dff", 402 )
engineReplaceModel(dff, 402)

txd = engineLoadTXD("tex/vehicles/copcarla.txd", 596 )
engineImportTXD(txd, 596)
dff = engineLoadDFF("tex/vehicles/copcarla.dff", 596 )
engineReplaceModel(dff, 596)
txd = engineLoadTXD("tex/vehicles/voodoo.txd", 412 )
engineImportTXD(txd, 412)
dff = engineLoadDFF("tex/vehicles/voodoo.dff", 412 )
engineReplaceModel(dff, 412)

txd = engineLoadTXD("tex/vehicles/landstalker.txd", 400 )
engineImportTXD(txd, 400)
dff = engineLoadDFF("tex/vehicles/landstalker.dff", 400 )
engineReplaceModel(dff, 400)

dff = engineLoadDFF("tex/vehicles/FCR-900.dff", 521 )
engineReplaceModel(dff, 521)
txd = engineLoadTXD("tex/vehicles/FCR-900.txd", 521 )
engineImportTXD(txd, 521)

txd = engineLoadTXD("tex/vehicles/sunrise.txd", 550 )
engineImportTXD(txd, 550)
dff = engineLoadDFF("tex/vehicles/sunrise.dff", 550 )
engineReplaceModel(dff, 550)
txd = engineLoadTXD("tex/vehicles/dune.txd", 573 )
engineImportTXD(txd, 573)
dff = engineLoadDFF("tex/vehicles/dune.dff", 573 )
engineReplaceModel(dff, 573)
]]
